# INBOX ZERO + SAFLA + WSJF Board
# Single source of truth: Retro Insights → Refinement → Backlog → Code → Metrics → Next Review
#
# Target Metrics:
# - Time retro insight → code commit: < 1 hour
# - % action items completed: > 80%
# - Context switches per day: < 5
# - Lead/cycle time: Track trend
# - Throughput: Track trend
# - WIP violations: < 5%
# - Experiments per sprint: > 3
# - % retro items → features: > 60%
# - Time to implement learning: < 1 week

metadata:
  version: "1.0"
  created: "2025-11-17"
  framework: "WSJF + SAFLA + Inbox Zero + Build-Measure-Learn"
  owner: "Orchestrator Circle"
  review_cadence: "Daily"

# =============================================================================
# PHASE 1: REVIEW (Retrospective Insights)
# =============================================================================
retrospective_insights:
  - id: "RETRO-001"
    date: "2025-11-17"
    source: "Agent conversation"
    insight: "Massive scope gap: WordPress, Flarum, trading platforms, Temporal not in SAFe structure"
    category: "Coverage Gap"
    impact: "HIGH"
    cost_of_delay: 90  # WSJF: Business value + time criticality + risk reduction
    job_size: 13       # Story points
    wsjf_score: 6.92   # 90/13
    status: "TO_REFINE"
    circles: ["seeker", "orchestrator"]
    linked_docs: []
    created_at: "2025-11-17T13:30:00Z"

  - id: "RETRO-002"
    date: "2025-11-17"
    source: "Agent conversation"
    insight: "Context-switching friction between Retro→Refinement→Backlog→Code→Metrics"
    category: "Process Friction"
    impact: "HIGH"
    cost_of_delay: 80
    job_size: 8
    wsjf_score: 10.0
    status: "TO_REFINE"
    circles: ["innovator", "orchestrator"]
    linked_docs: ["investing/agentic-flow/scripts/doc_query.py"]
    created_at: "2025-11-17T13:30:00Z"

  - id: "RETRO-003"
    date: "2025-11-17"
    source: "Agent conversation"
    insight: "doc_query.py lacks DoR/DoD, success criteria, retrospective feedback"
    category: "Technical Debt"
    impact: "MEDIUM"
    cost_of_delay: 40
    job_size: 5
    wsjf_score: 8.0
    status: "TO_REFINE"
    circles: ["assessor", "innovator"]
    linked_docs: ["investing/agentic-flow/scripts/doc_query.py"]
    created_at: "2025-11-17T13:30:00Z"

# =============================================================================
# PHASE 2: REFINEMENT (Backlog Grooming)
# =============================================================================
refinement_queue:
  - id: "REFINE-001"
    from_retro: "RETRO-001"
    title: "Comprehensive Platform Discovery & SAFe Migration"
    description: |
      Scan for WordPress, Flarum, trading platforms, Temporal implementations.
      Use gh CLI to discover all GitHub repos.
      Classify by SAFe lifecycle + assign circles.
    acceptance_criteria:
      - "All GitHub repos catalogued with SAFe lifecycle assignment"
      - "WordPress/Flarum installations discovered and migrated"
      - "Trading platforms (TradingView, Finviz, Interactive Brokers) integrated"
      - "Temporal workflow engine structure created"
      - "Circle ownership assigned for all platforms"
    dor:  # Definition of Ready
      - "GitHub PAT available and gh CLI authenticated"
      - "SAFe lifecycle criteria documented"
      - "Circle capacity validated for new assignments"
    dod:  # Definition of Done
      - "All platforms in code/{evaluating,emerging,investing,retiring}/"
      - "README.md with circle ownership per platform"
      - ".capex/ or .opex/ tracking folders created"
      - "Upstream sync configured for each platform"
      - "Updated .governance/circle-budget-allocation.json"
    estimated_effort: "13 story points"
    wsjf_score: 6.92
    status: "READY_FOR_BACKLOG"
    circles: ["seeker", "orchestrator", "analyst"]

  - id: "REFINE-002"
    from_retro: "RETRO-002"
    title: "Unified Interface: Eliminate Context-Switching"
    description: |
      Create single interface connecting:
      Retro docs → Kanban board → Code editor → Metrics dashboard
      Integrate with VSCode/Cursor/Windsurf/Zed
    acceptance_criteria:
      - "Single unified workspace in agentic-flow/interfaces/"
      - "IDE extensions for VSCode/Cursor/Windsurf/Zed"
      - "Metrics dashboard embedded in IDE"
      - "WSJF scoring visible in kanban view"
      - "< 5 context switches per day target met"
    dor:
      - "IDEs identified (VSCode, Cursor, Windsurf, Zed)"
      - "Metrics API available (from .goalie/)"
      - "Kanban board format defined (YAML)"
    dod:
      - "Unified interface at investing/agentic-flow/interfaces/unified-swarm-interface/"
      - "IDE extensions published"
      - "Metrics integration test passing"
      - "User documentation created"
      - "< 1 hour retro insight → code commit measured"
    estimated_effort: "8 story points"
    wsjf_score: 10.0
    status: "READY_FOR_BACKLOG"
    circles: ["innovator", "orchestrator"]

  - id: "REFINE-003"
    from_retro: "RETRO-003"
    title: "doc_query.py: Add DoR/DoD + Retrospective Integration"
    description: |
      Enhance doc_query.py with:
      - Success criteria (<1s search, >80% relevance)
      - DoR/DoD checklist
      - Retrospective insights capture
      - Link to WSJF board
    acceptance_criteria:
      - "Search performance < 1 second"
      - "Relevance score > 80%"
      - "DoR/DoD checklist in README"
      - "Retrospective insights logged to .goalie/insights_log.jsonl"
      - "Auto-link to WSJF board when creating action items"
    dor:
      - "Current doc_query.py functionality documented"
      - "Performance baseline established"
      - "Test suite exists"
    dod:
      - "Performance tests passing (< 1s)"
      - "Relevance tests passing (> 80%)"
      - "README.md updated with DoR/DoD"
      - "Integration tests with .goalie/ passing"
      - "No new .md files created (update existing docs only)"
    estimated_effort: "5 story points"
    wsjf_score: 8.0
    status: "READY_FOR_BACKLOG"
    circles: ["assessor", "innovator"]

# =============================================================================
# PHASE 3: BACKLOG (Prioritized Work Items)
# =============================================================================
backlog:
  now:  # Sprint: Current week
    - id: "NOW-001"
      title: "Install & Test Agentic Tooling"
      description: |
        Install agentic-jujutsu, neural-trader, governance crates.
        Test basic functionality.
        Create unified CLI at agentic-flow/tools/unified-cli/
      wsjf_score: 15.0  # Quick win, high value
      circles: ["innovator"]
      estimated_hours: 4
      dor_met: true
      linked_to: "REFINE-002"
      status: "TODO"
      
    - id: "NOW-002"
      title: "GitHub Repos Discovery (gh CLI)"
      description: "Use gh CLI to list all repos, classify by activity level"
      wsjf_score: 12.0
      circles: ["seeker", "analyst"]
      estimated_hours: 2
      dor_met: true
      linked_to: "REFINE-001"
      status: "TODO"

    - id: "NOW-003"
      title: "doc_query.py Performance Baseline"
      description: "Measure current performance and establish test suite"
      wsjf_score: 8.0
      circles: ["assessor"]
      estimated_hours: 3
      dor_met: true
      linked_to: "REFINE-003"
      status: "TODO"

  next:  # Sprint: Next 1-2 weeks
    - id: "NEXT-001"
      title: "WordPress/Flarum/Plugins Ecosystem Activation"
      wsjf_score: 6.92
      circles: ["seeker", "orchestrator"]
      estimated_hours: 13
      linked_to: "REFINE-001"
      status: "BACKLOG"

    - id: "NEXT-002"
      title: "Trading Platforms Integration (TradingView, Finviz, IB)"
      wsjf_score: 6.5
      circles: ["analyst", "innovator"]
      estimated_hours: 21
      linked_to: "REFINE-001"
      status: "BACKLOG"

    - id: "NEXT-003"
      title: "Temporal Workflow Implementation"
      wsjf_score: 7.0
      circles: ["orchestrator", "innovator"]
      estimated_hours: 34
      linked_to: "REFINE-001"
      status: "BACKLOG"

  later:  # Sprint: Beyond 2 weeks
    - id: "LATER-001"
      title: "DecisionCall.com Automation"
      wsjf_score: 5.0
      circles: ["analyst", "orchestrator"]
      estimated_hours: 21
      linked_to: null
      status: "BACKLOG"

    - id: "LATER-002"
      title: "Donor Advised Funding Integration"
      wsjf_score: 4.5
      circles: ["seeker", "analyst"]
      estimated_hours: 13
      linked_to: null
      status: "BACKLOG"

# =============================================================================
# PHASE 4: CODE (Active Development)
# =============================================================================
in_progress:
  - id: "WIP-001"
    title: "WSJF Board Creation & Documentation"
    description: "This board itself - creating single source of truth"
    assignee: "orchestrator"
    started_at: "2025-11-17T13:30:00Z"
    estimated_completion: "2025-11-17T14:00:00Z"
    linked_commits: []
    status: "IN_PROGRESS"

# =============================================================================
# PHASE 5: MEASUREMENT (Metrics & Analytics)
# =============================================================================
metrics:
  process_metrics:
    time_retro_to_code:
      target: "< 1 hour"
      current: null  # To be measured
      unit: "minutes"
      trend: []
      
    action_items_completion_rate:
      target: "> 80%"
      current: null
      unit: "percent"
      trend: []
      
    context_switches_per_day:
      target: "< 5"
      current: null
      unit: "count"
      trend: []

  flow_metrics:
    lead_time:
      target: "Track trend"
      current: null
      unit: "days"
      trend: []
      
    cycle_time:
      target: "Track trend"
      current: null
      unit: "days"
      trend: []
      
    throughput:
      target: "Track trend"
      current: null
      unit: "items/week"
      trend: []
      
    wip_violations:
      target: "< 5%"
      current: 0
      unit: "percent"
      trend: []

  learning_metrics:
    experiments_per_sprint:
      target: "> 3"
      current: 0
      unit: "count"
      trend: []
      
    retro_items_to_features:
      target: "> 60%"
      current: null
      unit: "percent"
      trend: []
      
    time_to_implement_learning:
      target: "< 1 week"
      current: null
      unit: "days"
      trend: []

  last_updated: "2025-11-17T13:30:00Z"

# =============================================================================
# PHASE 6: NEXT REVIEW (Feedback Loop)
# =============================================================================
next_review:
  scheduled_at: "2025-11-18T09:00:00Z"
  agenda:
    - "Review NOW items completion"
    - "Measure time from RETRO-002 insight to code commit"
    - "Validate metrics collection automation"
    - "Update WSJF scores based on learnings"
    - "Identify new retrospective insights"
  participants: ["orchestrator", "analyst", "assessor"]
  expected_outcomes:
    - "All NOW items completed or explicitly moved to NEXT"
    - "At least 3 new retrospective insights captured"
    - "Metrics dashboard updated with real data"
    - "Next sprint planning complete"

# =============================================================================
# INTEGRATION POINTS
# =============================================================================
integrations:
  doc_query:
    script: "investing/agentic-flow/scripts/doc_query.py"
    command: "python3 doc_query.py --link-issue <issue_id>"
    
  metrics_log:
    file: ".goalie/metrics_log.jsonl"
    append_command: "echo '{...}' >> .goalie/metrics_log.jsonl"
    
  insights_log:
    file: ".goalie/insights_log.jsonl"
    append_command: "echo '{...}' >> .goalie/insights_log.jsonl"
    
  kanban_board:
    file: ".goalie/KANBAN_BOARD.yaml"
    sync_command: "python3 scripts/sync_wsjf_to_kanban.py"
    
  ide_integration:
    vscode: ".vscode/settings.json"
    cursor: ".cursor/settings.json"
    windsurf: ".windsurf/settings.json"
    zed: ".zed/settings.json"

# =============================================================================
# AUTOMATION RULES
# =============================================================================
automation:
  - trigger: "retrospective_insight_added"
    action: "Create REFINE item with auto-calculated WSJF score"
    
  - trigger: "refinement_dor_met"
    action: "Move to BACKLOG with NOW/NEXT/LATER classification"
    
  - trigger: "backlog_item_started"
    action: "Log start time to metrics_log.jsonl"
    
  - trigger: "code_commit_linked"
    action: "Calculate time_retro_to_code and update metrics"
    
  - trigger: "wip_limit_exceeded"
    action: "Alert orchestrator circle"
    
  - trigger: "daily_review_time"
    action: "Generate metrics dashboard update"

# =============================================================================
# WSJF CALCULATION REFERENCE
# =============================================================================
wsjf_formula: |
  WSJF = Cost of Delay / Job Size
  
  Cost of Delay = Business Value + Time Criticality + Risk Reduction/Opportunity Enablement
  
  Scoring (Fibonacci):
  - Business Value: 1, 2, 3, 5, 8, 13, 20
  - Time Criticality: 1, 2, 3, 5, 8, 13, 20
  - Risk Reduction: 1, 2, 3, 5, 8, 13, 20
  - Job Size (Story Points): 1, 2, 3, 5, 8, 13, 21
  
  Higher WSJF = Higher Priority
