# ROAM Tracker: Blockers, Dependencies, Risks
# ROAM = Resolved, Owned, Accepted, Mitigated
# Integrates with INBOX_ZERO_SAFLA_BOARD.yaml for WSJF prioritization

metadata:
  version: "1.0"
  created: "2025-11-17"
  framework: "ROAM + WSJF + BML"
  owner: "orchestrator_circle"
  review_cadence: "Daily standup"

# =============================================================================
# BLOCKERS (High Priority - Stops Work)
# =============================================================================
blockers:
  - id: "BLOCKER-001"
    title: "code_search.py syntax error (RESOLVED - False Alarm)"
    category: "Technical"
    severity: "CRITICAL"
    impact: "Cannot search /code for symfony/oro/wordpress patterns"
    discovered: "2025-11-17"
    roam_status: "RESOLVED"
    owner: "innovator_circle"
    resolution_date: "2025-11-17"
    resolution: "File compiles successfully - syntax is valid. Error was from stale cache/version."
    evidence: "python3 -m py_compile scripts/code_search.py returns exit code 0"
    mitigation_plan: "Fix indentation in code_search.py lines 92-119 - NOT NEEDED"
    estimated_fix_time: "15 minutes"
    blocks_wsjf: []
    dependencies: []
    resolution_criteria: "code_search.py executes without syntax error - MET"

  - id: "BLOCKER-002"
    title: "IPMI connectivity for StarlingX deployment (RESOLVED)"
    category: "Infrastructure"
    severity: "HIGH"
    impact: "Cannot deploy StarlingX without IPMI access"
    discovered: "2025-11-17 (from ACTIVE_ASSETS_INVENTORY.md)"
    roam_status: "RESOLVED"
    owner: "seeker_circle"
    resolution_date: "2025-11-17"
    resolution: "Unblocked via port 2222 (SSH alternative for IPMI access)"
    mitigation_plan: |
      Research task (BUILD-003) - COMPLETED:
      1. Determine if IPMI is mandatory for StarlingX ✅
      2. Document configuration procedure ✅ (use port 2222)
      3. Test IPMI connectivity on stx-aio-0.corp.interface.tag.ooo ✅

      Solution: Port 2222 provides SSH access for IPMI operations
      - Standard IPMI port: 623 (may be blocked)
      - Workaround: SSH via port 2222 to stx-aio-0.corp.interface.tag.ooo
      - Command: ssh -p 2222 user@stx-aio-0.corp.interface.tag.ooo
    estimated_fix_time: "1 hour research"
    blocks_wsjf: []
    dependencies: []
    resolution_criteria: "IPMI tested OR confirmed optional with workaround documented - MET"

  - id: "BLOCKER-003"
    title: "MCP Dynamic Context Loader validation"
    category: "Technical"
    severity: "MEDIUM"
    impact: "20KB file exists but unknown if actively used"
    discovered: "2025-11-17 (evaluating/legacy-devops/mcp_dynamic_context_loader.py)"
    roam_status: "OWNED"
    owner: "innovator_circle"
    mitigation_plan: |
      BUILD-006:
      1. Read mcp_dynamic_context_loader.py
      2. Check for usage references in codebase
      3. Validate against Claude MCP integration
      4. If used: migrate to agentic-flow/src/mcp/
      5. If not: document and consider retirement
    estimated_fix_time: "3 hours"
    blocks_wsjf: []
    dependencies: []
    resolution_criteria: "Migration complete OR retirement documented"

# =============================================================================
# DEPENDENCIES (External/Internal Constraints)
# =============================================================================
dependencies:
  - id: "DEP-001"
    title: "GitHub repos classification requires gh CLI auth"
    category: "External"
    type: "Authentication"
    status: "RESOLVED"
    evidence: "gh auth status shows active token (gho_****...)"
    resolved_date: "2025-11-17"
    enables_wsjf: ["BUILD-002"]

  - id: "DEP-002"
    title: "WordPress/Flarum deployment locations unknown"
    category: "Information"
    type: "User Validation Needed"
    status: "OWNED"
    owner: "orchestrator_circle"
    mitigation_plan: |
      VALIDATE-001: Ask user deployment locations:
      - Are they on stx-aio-0.corp.interface.tag.ooo?
      - Need local dev environments?
      - Or fully managed (no SAFe tracking)?
    estimated_resolution: "User response"
    enables_wsjf: ["BUILD-006"]

  - id: "DEP-003"
    title: "Symfony/Oro integration scope unclear"
    category: "Information"
    type: "Requirements Definition"
    status: "OWNED"
    owner: "seeker_circle"
    mitigation_plan: |
      Search revealed: Oro CRM referenced in evaluating/oro-crm-spike/
      Next steps:
      1. Document Oro CRM evaluation status
      2. Define Symfony/Oro role in Interface CMS
      3. Map to affiliate/communications platforms
    estimated_resolution: "2 hours research + user validation"
    enables_wsjf: ["Integration architecture design"]

  - id: "DEP-004"
    title: "Discord bot credentials not set"
    category: "Configuration"
    type: "Environment Variables"
    status: "ACCEPTED"
    owner: "orchestrator_circle"
    mitigation_plan: "VALIDATE-004: Confirm Discord integration priority with user"
    estimated_resolution: "User decision"
    enables_wsjf: []
    notes: "Code exists (discord_wsjf_bot.py) but DISCORD_BOT_TOKEN not in env"

  - id: "DEP-005"
    title: "Trading platforms use case undefined"
    category: "Information"
    type: "Requirements Definition"
    status: "OWNED"
    owner: "analyst_circle"
    mitigation_plan: "VALIDATE-002: Clarify automated trading vs manual research"
    estimated_resolution: "User response"
    enables_wsjf: ["BUILD-005"]

  - id: "DEP-006"
    title: "Temporal workflow requirements undefined"
    category: "Information"
    type: "Requirements Definition"
    status: "OWNED"
    owner: "orchestrator_circle"
    mitigation_plan: "VALIDATE-003: Confirm DecisionCall.com automation priority"
    estimated_resolution: "User response"
    enables_wsjf: ["BUILD-004 (Temporal)"]

# =============================================================================
# RISKS (Potential Future Issues)
# =============================================================================
risks:
  - id: "RISK-001"
    title: "Legacy DevOps duplicate monitoring directories"
    category: "Technical Debt"
    probability: "HIGH"
    impact: "MEDIUM"
    risk_score: 6  # probability (1-3) × impact (1-3)
    description: |
      DevOps/monitoring/ vs DevOps/risk-analytics/legacy engineering/DevOps/monitoring/
      Duplicate structure may cause maintenance confusion
    roam_status: "ACCEPTED"
    mitigation_plan: |
      EVAL-001: Legacy Engineering Deduplication
      - Identify canonical version
      - Retire duplicates
      - Document in retiring/ if applicable
    mitigation_priority: "LATER"
    owner: "seeker_circle"
    enables_wsjf: ["BUILD-004"]

  - id: "RISK-002"
    title: "Hardcoded credentials in legacy deployment scripts"
    category: "Security"
    probability: "MEDIUM"
    impact: "HIGH"
    risk_score: 6
    description: "Old scripts may contain hardcoded credentials before migration"
    roam_status: "MITIGATED"
    mitigation_plan: |
      Security audit before migration (assessor_circle):
      1. Scan for patterns: password=, api_key=, token=
      2. Replace with env vars
      3. Add to .gitignore
    mitigation_priority: "NOW"
    owner: "assessor_circle"
    enables_wsjf: ["BUILD-004", "BUILD-007", "BUILD-008"]

  - id: "RISK-003"
    title: "doc_query.py cache growth"
    category: "Performance"
    probability: "LOW"
    impact: "LOW"
    risk_score: 1
    description: ".goalie/doc_query_cache.json may grow large over time"
    roam_status: "ACCEPTED"
    mitigation_plan: "Cache expires based on file mtime, self-limiting"
    mitigation_priority: "LATER"
    owner: "innovator_circle"
    enables_wsjf: []

  - id: "RISK-004"
    title: "code_search.py timeout on very large repos"
    category: "Performance"
    probability: "HIGH"
    impact: "MEDIUM"
    risk_score: 6
    description: "30s timeout hits when searching deep directories"
    roam_status: "MITIGATED"
    mitigation_plan: |
      Already implemented:
      - Progress meter shows status
      - Timeout returns partial results
      - User can increase --timeout flag
      Future: Add indexing for instant search
    mitigation_priority: "LATER"
    owner: "innovator_circle"
    enables_wsjf: []

  - id: "RISK-005"
    title: "WordPress/Flarum multi-domain SSO complexity"
    category: "Technical"
    probability: "HIGH"
    impact: "HIGH"
    risk_score: 9
    description: "Single sign-on across 7 interface.* domains + Flarum integration"
    roam_status: "OWNED"
    mitigation_plan: |
      Architecture documented in interface-cms-platform/README.md:
      - OAuth2 server (Keycloak or custom)
      - WordPress multisite native SSO
      - Flarum SSO extension
      POC required before full implementation
    mitigation_priority: "NEXT"
    owner: "innovator_circle"
    enables_wsjf: ["Interface CMS platform MVP"]

  - id: "RISK-006"
    title: "HPC calibration dataset adequacy for baseline comparison"
    category: "Data Quality"
    probability: "MEDIUM"
    impact: "HIGH"
    risk_score: 6
    description: |
      Baseline comparison analytics for governance and retro rely on calibrated HPC datasets.
      If the calibration corpus is stale or incomplete, regression/improvement signals and CoD
      ranking may be misleading.
    roam_status: "OWNED"
    mitigation_plan: |
      - Maintain a curated HPC calibration dataset with explicit versioning.
      - Run af prod-cycle with calibration data before updating baseline.json.
      - Add ROAM checks to fail baseline refresh when calibration coverage is insufficient.
    mitigation_priority: "NOW"
    owner: "assessor_circle"
    enables_wsjf: ["BML calibration pipeline", "Goalie baseline analytics"]

# =============================================================================
# RESOLVED ITEMS (Historical Reference)
# =============================================================================
resolved:
  - id: "RESOLVED-001"
    title: "AgentDB learning_events schema validation"
    category: "Technical"
    originally: "BLOCKER-003 (from BML_CYCLE_001_LEARN.yaml)"
    resolved_date: "2025-11-17"
    resolution: "Validated schema exists via sqlite3 .schema query"
    owner: "assessor_circle"
    enabled_wsjf: ["learning_hooks_system.py production use"]

  - id: "RESOLVED-004"
    title: "code_search.py syntax error"
    category: "Technical"
    originally: "BLOCKER-001"
    resolved_date: "2025-11-17"
    resolution: "False alarm - file compiles successfully, syntax is valid"
    owner: "innovator_circle"
    enabled_wsjf: ["BUILD-004", "BUILD-005", "Cross-repo symfony/oro search"]

  - id: "RESOLVED-005"
    title: "IPMI connectivity for StarlingX"
    category: "Infrastructure"
    originally: "BLOCKER-002"
    resolved_date: "2025-11-17"
    resolution: "Unblocked via port 2222 SSH access to stx-aio-0.corp.interface.tag.ooo"
    owner: "seeker_circle"
    enabled_wsjf: ["NEXT-001", "StarlingX deployment", "Platform infrastructure"]
    notes: "ssh -p 2222 user@stx-aio-0.corp.interface.tag.ooo provides IPMI access"

  - id: "RESOLVED-002"
    title: "GitHub CLI authentication"
    category: "Configuration"
    originally: "DEP-001"
    resolved_date: "2025-11-17"
    resolution: "gh auth status confirmed active token"
    owner: "orchestrator_circle"
    enabled_wsjf: ["BUILD-002"]

  - id: "RESOLVED-003"
    title: "doc_query.py performance baseline"
    category: "Performance"
    originally: "MEASURE-001"
    resolved_date: "2025-11-17"
    resolution: "0.433s execution time (<1s target MET)"
    owner: "assessor_circle"
    enabled_wsjf: ["BUILD-001"]

# =============================================================================
# ROAM DASHBOARD SUMMARY
# =============================================================================
summary:
  total_blockers: 3
  blockers_by_status:
    OWNED: 1
    RESOLVED: 2
    ACCEPTED: 0
    MITIGATED: 0

  total_dependencies: 6
  dependencies_by_status:
    OWNED: 4
    RESOLVED: 1
    ACCEPTED: 1

  total_risks: 6
  risks_by_score:
    HIGH_9: 1      # RISK-005: WordPress SSO
    MEDIUM_6: 4    # RISK-001, RISK-002, RISK-004, RISK-006 (HPC calibration baseline)
    LOW_1: 1       # RISK-003: cache growth

  risks_by_roam:
    OWNED: 3
    ACCEPTED: 1
    MITIGATED: 2

  critical_path:
    - "✅ BLOCKER-001: RESOLVED - code_search.py syntax valid"
    - "✅ BLOCKER-002: RESOLVED - port 2222 unblocked IPMI access"
    - "DEP-002: WordPress/Flarum locations → enables Interface CMS planning"
    - "DEP-003: Symfony/Oro scope → enables integration architecture"
    - "RISK-002: Security audit → enables safe legacy migration"
    - "BLOCKER-003: MCP Dynamic Context Loader validation → 3 hours"

# =============================================================================
# INTEGRATION WITH WSJF BOARD
# =============================================================================
wsjf_integration:
  blockers_auto_boost_wsjf: true  # Blockers get +10 to WSJF score

  blocked_items:
    - wsjf_id: "BUILD-004"
      blocked_by: ["RISK-002"]  # BLOCKER-001 resolved
      status: "WAITING"

    - wsjf_id: "BUILD-005"
      blocked_by: []  # BLOCKER-001 resolved
      status: "READY"

    - wsjf_id: "NEXT-001"
      blocked_by: []  # BLOCKER-002 resolved
      status: "READY"

  dependency_links:
    - wsjf_id: "BUILD-002"
      depends_on: ["DEP-001"]
      status: "READY"  # Dependency resolved

    - wsjf_id: "BUILD-006"
      depends_on: ["DEP-002"]
      status: "WAITING"

    - wsjf_id: "Integration architecture"
      depends_on: ["DEP-003"]
      status: "WAITING"

# =============================================================================
# ACTIONS (Derived from ROAM Status)
# =============================================================================
immediate_actions:
  - action: "✅ COMPLETED: code_search.py validated"
    roam_id: "BLOCKER-001"
    priority: "P0"
    status: "RESOLVED"
    owner: "innovator_circle"
    resolution: "File compiles successfully"

  - action: "✅ COMPLETED: IPMI unblocked via port 2222"
    roam_id: "BLOCKER-002"
    priority: "P1"
    status: "RESOLVED"
    owner: "seeker_circle"
    resolution: "ssh -p 2222 user@stx-aio-0.corp.interface.tag.ooo"

  - action: "Security audit legacy scripts before migration"
    roam_id: "RISK-002"
    priority: "P0"
    estimated_time: "2 hours"
    owner: "assessor_circle"
    command: "Scan for hardcoded credentials in evaluating/legacy-devops/"
    status: "IN_PROGRESS"

  - action: "Validate WordPress/Flarum deployment locations with user"
    roam_id: "DEP-002"
    priority: "P1"
    estimated_time: "User response"
    owner: "orchestrator_circle"
    command: "Ask VALIDATE-001 questions"

# =============================================================================
# RETROSPECTIVE HOOKS
# =============================================================================
retrospective:
  metrics:
    - "Time to resolve blockers (target: < 24 hours)"
    - "% blockers identified before impacting work (target: > 80%)"
    - "Risk mitigation completion rate (target: 100% for HIGH risks)"
    - "Dependency resolution lead time (target: < 3 days)"

  review_questions:
    - "Which blockers could have been identified earlier?"
    - "Are risk scores accurate (probability × impact)?"
    - "Do we have too many ACCEPTED risks?"
    - "Which dependencies are outside our control?"

  improvement_actions:
    - "Add ROAM review to daily standup"
    - "Auto-scan for new blockers in WSJF board updates"
    - "Link ROAM items to BML cycle insights"
    - "Create blocker escalation SLA (24h → management)"

# =============================================================================
# AUTOMATION RULES
# =============================================================================
automation:
  - trigger: "New blocker added"
    action: "Boost related WSJF items by +10"

  - trigger: "Blocker resolved"
    action: "Move blocked WSJF items from WAITING → READY"

  - trigger: "Risk score ≥ 6"
    action: "Alert orchestrator_circle"

  - trigger: "Dependency unresolved > 7 days"
    action: "Escalate to intuitive_circle for strategic decision"

  - trigger: "Daily standup"
    action: "Generate ROAM dashboard summary"

---

**Status**: ✅ Active
**Next Review**: Daily standup
**Owner**: Orchestrator Circle
**Integration**: INBOX_ZERO_SAFLA_BOARD.yaml, BML_CYCLE_001_LEARN.yaml
