---
deployment:
  tasks:
    - rm -rf /home/ogov/public_html/prefig/assets
    - mkdir -p /home/ogov/public_html/prefig
    - /bin/cp -R swarm-core-app/dist/* /home/ogov/public_html/prefig/
    - /bin/cp -f swarm-core-app/dist/.htaccess /home/ogov/public_html/prefig/
