#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: stx-aio-0
    username: sysadmin
    password: "$6$rounds=4096$encryptedpasswd...replace_me..." # User must set this or we provide a default weak one to be changed
    realname: Sysadmin
  locale: en_US.UTF-8
  keyboard:
    layout: us
  ssh:
    install-server: true
    allow-pw: true
    authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHnFoXy9HfnkuNIicAFCj/q9Q3PkZS+3k0FdIGkqqkSP shahroozbhopti@Mac.lan
  network:
    version: 2
    ethernets:
      eno1:
        dhcp4: false
      eno2:
        dhcp4: false
    bonds:
      bond0:
        interfaces:
          - eno1
          - eno2
        parameters:
          mode: 802.3ad
          lacp-rate: fast
          gvrp: true # Added for LACP resiliency
        addresses:
          - 23.92.79.2/30
        gateway4: 23.92.79.1
        nameservers:
          addresses:
            - 8.8.8.8
            - 1.1.1.1
  storage:
    layout:
      name: lvm
  packages:
    - bridge-utils
    - vlan
    - python3
    - curl
    - wget
  late-commands:
    - "sed -i 's/#Port 22/Port 2222/' /target/etc/ssh/sshd_config"
    - "sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /target/etc/ssh/sshd_config" # Temporary for bootstrap
