allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  better-sqlite3: set this to true or false
  puppeteer: set this to true or false
  tesseract.js: set this to true or false
