#!/bin/bash
# auto-ticket-generator.sh - Generate improvement tickets when quality drops
# Creates GitHub issues or local tickets for quality improvements

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Configuration
TICKETS_DIR="$PROJECT_ROOT/.github/auto-tickets"
METRICS_FILE="/tmp/robust-metrics/build-metrics.json"
COMPONENT_FILE="/tmp/component-adoption.json"

# Create tickets directory
mkdir -p "$TICKETS_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Generate improvement ticket
generate_ticket() {
    local current_quality="$1"
    local threshold="${2:-80}"
    local target="${3:-95}"
    
    if [[ $(echo "$current_quality < $threshold" | bc -l) -eq 1 ]]; then
        local gap=$((threshold - current_quality))
        local ticket_id="quality-$(date +%s)"
        local ticket_file="$TICKETS_DIR/${ticket_id}.md"
        
        # Create ticket content
        cat > "$ticket_file" << EOF
# 🚨 Quality Gate Failure - Auto-generated Improvement Ticket

**Ticket ID**: $ticket_id  
**Generated**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")  
**Priority**: High  

## 📊 Quality Metrics

- **Current Quality**: ${current_quality}%
- **Required Threshold**: ${threshold}%
- **Target Quality**: ${target}%
- **Quality Gap**: ${gap}%

## 🔍 Root Cause Analysis

EOF
        
        # Analyze missing components
        if [[ -f "$COMPONENT_FILE" ]]; then
            echo "### Missing ROBUST Components" >> "$ticket_file"
            echo "" >> "$ticket_file"
            
            local missing_components=0
            while IFS= read -r component; do
                local name=$(echo "$component" | jq -r '.name')
                local desc=$(echo "$component" | jq -r '.description')
                
                echo "- [ ] **$name** (+20%): $desc" >> "$ticket_file"
                missing_components=$((missing_components + 1))
            done < <(jq -r '.components[] | select(.implemented == false)' "$COMPONENT_FILE")
            
            echo "" >> "$ticket_file"
            echo "**Impact**: Each missing component contributes 20% to overall quality" >> "$ticket_file"
            echo "" >> "$ticket_file"
        fi
        
        # Add specific recommendations
        cat >> "$ticket_file" << EOF
## 🎯 Recommended Actions

### Immediate (This Sprint)
1. **Add Pre-flight Checks**
   - Implement \`check_prerequisites()\` function
   - Validate dependencies (jq, python3, curl, lsof)
   - Check port availability before starting
   - Exit with semantic codes (60, 110, 11)

2. **Implement Bounded Reasoning**
   - Add \`create_contract()\` for process bounds
   - Use \`run_bounded_stream()\` wrapper
   - Set explicit time limits for all loops
   - Replace \`while true\` with bounded iterations

### Next Sprint
3. **Add ETA Tracking**
   - Call \`update_progress()\` at each step
   - Emit progress with \`emit_progress_update()\`
   - Show countdown timers instead of infinite waits
   - Display remaining time to user

4. **Implement TDD Logging**
   - Add \`log_tdd()\` for red-green-refactor cycles
   - Log each attempt and outcome
   - Create traceability for debugging
   - Store in \`/tmp/tdd-history.jsonl\`

### Following Sprint
5. **Fix Process Cleanup**
   - Use \`wait \$PID\` after kill signals
   - Ensure proper termination
   - Clean up temporary files
   - Handle orphaned processes

## 📈 Success Criteria

- [ ] Quality reaches ${threshold}% (can merge)
- [ ] Quality reaches ${target}% (fully robust)
- [ ] All CI/CD passes consistently
- [ ] No more quality gate failures

## 🔗 Related Resources

- [ROBUST Implementation Guide](docs/ROBUST-IMPLEMENTATION.md)
- [Quality Metrics Dashboard](metrics-dashboard.json)
- [Component Adoption Tracker](_SYSTEM/_AUTOMATION/component-adoption-tracker.sh)

## 📝 Notes

This ticket was auto-generated due to quality gate failure.  
Each implemented component improves quality by 20%.  
Focus on the highest impact items first.

---
*Generated by auto-ticket-generator.sh*
EOF
        
        echo -e "${GREEN}✅ Ticket generated: $ticket_file${NC}"
        echo "   Quality gap: ${gap}%"
        
        # Try to create GitHub issue if gh CLI is available
        if command -v gh >/dev/null 2>&1; then
            create_github_issue "$ticket_file" "$current_quality" "$threshold"
        fi
        
        return 0
    else
        echo -e "${GREEN}✅ Quality gate passed (${current_quality}% >= ${threshold}%)${NC}"
        return 1
    fi
}

# Create GitHub issue
create_github_issue() {
    local ticket_file="$1"
    local current_quality="$2"
    local threshold="$3"
    
    echo "Creating GitHub issue..."
    
    # Extract title and body
    local title="Quality Gate Failure: ${current_quality}% < ${threshold}%"
    local body=$(cat "$ticket_file")
    
    # Create issue
    if gh issue create --title "$title" --body "$body" --label "quality-gate,auto-generated,high-priority"; then
        echo -e "${GREEN}✅ GitHub issue created${NC}"
    else
        echo -e "${YELLOW}⚠️ Failed to create GitHub issue${NC}"
    fi
}

# Check for existing tickets
check_existing_tickets() {
    local current_quality="$1"
    
    echo ""
    echo "Existing Quality Tickets:"
    echo "─────────────────────────────────────────────────────────────────"
    
    local open_tickets=0
    for ticket in "$TICKETS_DIR"/*.md; do
        if [[ -f "$ticket" ]]; then
            local created=$(grep "Generated:" "$ticket" | cut -d' ' -f2)
            local status="Open"
            
            # Check if ticket is resolved (quality improved)
            local ticket_quality=$(grep "Current Quality:" "$ticket" | grep -o '[0-9]*')
            if [[ -n "$ticket_quality" ]] && [[ $(echo "$current_quality > $ticket_quality" | bc -l) -eq 1 ]]; then
                status="Resolved"
            fi
            
            echo "  $(basename "$ticket" .md): $status (Created: $created)"
            
            if [[ "$status" == "Open" ]]; then
                open_tickets=$((open_tickets + 1))
            fi
        fi
    done
    
    if [[ $open_tickets -eq 0 ]]; then
        echo -e "${GREEN}  No open quality tickets${NC}"
    else
        echo -e "${YELLOW}  $open_tickets open ticket(s) need attention${NC}"
    fi
    
    echo ""
}

# Generate quality trend report
generate_quality_trend() {
    if [[ ! -f "$METRICS_FILE" ]]; then
        echo "No metrics data available"
        return 1
    fi
    
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo -e "${BLUE}  QUALITY TREND ANALYSIS${NC}"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    
    # Calculate statistics
    local total_runs=$(jq '.summary.total_runs' "$METRICS_FILE")
    local avg_quality=$(jq '.summary.avg_quality' "$METRICS_FILE")
    local last_quality=$(jq '.summary.last_quality' "$METRICS_FILE")
    local trend=$(jq '.summary.trend' "$METRICS_FILE")
    
    printf "%-20s %s\n" "Total Runs:" "$total_runs"
    printf "%-20s %.1f%%\n" "Average Quality:" "$avg_quality"
    printf "%-20s %s%%\n" "Last Quality:" "$last_quality"
    
    if (( $(echo "$trend > 0" | bc -l) )); then
        printf "%-20s %s\n" "Trend:" "↑ Improving (+${trend}%)"
    elif (( $(echo "$trend < 0" | bc -l) )); then
        printf "%-20s %s\n" "Trend:" "↓ Declining (${trend}%)"
    else
        printf "%-20s %s\n" "Trend:" "→ Stable"
    fi
    
    echo ""
    
    # Show quality over time
    echo "Quality History (last 10 runs):"
    echo "─────────────────────────────────────────────────────────────────"
    
    jq -r '
        .runs[-10:] | reverse | .[] |
        "\(.timestamp | strftime("%m-%d %H:%M")) | \(.quality_pct | floor)%"
    ' "$METRICS_FILE" | while read -r line; do
        local pct=$(echo "$line" | grep -o '[0-9]*%')
        local bar=""
        
        # Create simple bar chart
        for i in $(seq 1 $((${pct%\%} / 5))); do
            bar+="█"
        done
        
        printf "%-15s | %-20s %s\n" "$line" "$bar" "$pct"
    done
    
    echo ""
}

# Main execution
case "${1:-check}" in
    "check")
        # Get current quality
        if [[ -f "$METRICS_FILE" ]]; then
            current_quality=$(jq '.summary.last_quality' "$METRICS_FILE")
        else
            echo "No metrics available. Run cascade-tunnel first."
            exit 1
        fi
        
        # Check existing tickets
        check_existing_tickets "$current_quality"
        
        # Generate new ticket if needed
        if generate_ticket "$current_quality" "${2:-80}" "${3:-95}"; then
            echo -e "${RED}🚨 Action required: Review improvement ticket${NC}"
        fi
        
        # Show trend
        generate_quality_trend
        ;;
    "generate")
        # Force generate ticket
        current_quality="${2:-0}"
        generate_ticket "$current_quality" "${3:-80}" "${4:-95}"
        ;;
    "list")
        check_existing_tickets "${2:-0}"
        ;;
    "trend")
        generate_quality_trend
        ;;
    *)
        echo "Usage: $0 {check|generate|list|trend} [quality] [threshold] [target]"
        exit 1
        ;;
esac
