#!/usr/bin/env bash
#
# Portal Check Automation with Paperclip + WSJF Routing
# Runs daily at 9 AM via LaunchAgent
#
# Purpose: Eliminate manual portal checks by automating:
# 1. Search legal folder for arbitration/utilities/hearing mentions
# 2. Route findings to WSJF risk matrix
# 3. Update ROAM tracker automatically
#
# Usage:
#   ./portal-check-auto.sh --case-id 26CV005596-590
#
# Dependencies:
#   - Paperclip CLI: npm install -g @paperclip/cli
#   - ruflo CLI: npm install -g ruflo
#   - @claude-flow/cli: npm install -g @claude-flow/cli

set -euo pipefail

# Configuration
CASE_ID="${1:-26CV005596-590}"
LEGAL_FOLDER="/Users/shahroozbhopti/Documents/Personal/CLT/MAA/Uptown/BHOPTI-LEGAL"
LOG_FILE="$HOME/Library/Logs/portal-check.log"
ROAM_TRACKER="/Users/shahroozbhopti/Documents/code/investing/agentic-flow/docs/110-frazier/ROAM_TRACKER.yaml"

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "🚀 Starting portal check automation for case $CASE_ID"

# Step 1: Check if Paperclip is installed
if ! command -v paperclip &> /dev/null; then
    log "⚠️ Paperclip CLI not found. Installing..."
    npm install -g @paperclip/cli >> "$LOG_FILE" 2>&1
    log "✅ Paperclip CLI installed"
fi

# Step 2: Index legal folder (if not already indexed)
if [ ! -d "$LEGAL_FOLDER/.paperclip" ]; then
    log "📁 Indexing legal folder (first run)..."
    paperclip index \
        --path "$LEGAL_FOLDER" \
        --recursive \
        --ocr-enabled \
        >> "$LOG_FILE" 2>&1
    log "✅ Legal folder indexed"
else
    log "📁 Legal folder already indexed, updating..."
    paperclip index --path "$LEGAL_FOLDER" --update >> "$LOG_FILE" 2>&1
fi

# Step 3: Search for critical terms (arbitration, utilities, hearing)
log "🔍 Searching for arbitration date mentions..."
SEARCH_RESULTS=$(paperclip search \
    "arbitration OR utilities OR hearing" \
    --case "$CASE_ID" \
    --since yesterday \
    --json 2>/dev/null || echo '[]')

# Step 4: Parse results and check for new findings
NEW_FINDINGS=$(echo "$SEARCH_RESULTS" | jq '. | length')

if [ "$NEW_FINDINGS" -gt 0 ]; then
    log "🎯 Found $NEW_FINDINGS new mentions! Routing to WSJF..."
    
    # Step 5: Store in ruflo memory for WSJF routing
    echo "$SEARCH_RESULTS" | jq -c '.[]' | while read -r result; do
        FILENAME=$(echo "$result" | jq -r '.filename')
        SNIPPET=$(echo "$result" | jq -r '.snippet')
        
        log "  - $FILENAME: $SNIPPET"
        
        # Store in memory
        npx ruflo memory store \
            --key "legal-search-$(date +%Y%m%d-%H%M%S)" \
            --value "$result" \
            --namespace patterns \
            >> "$LOG_FILE" 2>&1
    done
    
    # Step 6: Route to WSJF risk update
    log "🎯 Routing to WSJF risk matrix..."
    npx ruflo hooks route \
        --task "WSJF risk update: $NEW_FINDINGS new legal mentions" \
        --context "portal-check-auto" \
        >> "$LOG_FILE" 2>&1
    
    # Step 7: Update ROAM tracker with HIGH risk escalation
    if [ -f "$ROAM_TRACKER" ]; then
        log "📝 Updating ROAM tracker..."
        # Add a new risk entry (simplified YAML append)
        cat >> "$ROAM_TRACKER" << EOF

# AUTO-GENERATED by portal-check-auto.sh on $(date +'%Y-%m-%d %H:%M:%S')
R-2026-$(date +%j):
  description: "New legal mentions found: $NEW_FINDINGS items"
  priority: HIGH
  wsjf: 40.0
  source: "portal-check-auto"
  findings:
$(echo "$SEARCH_RESULTS" | jq -r '.[] | "    - \(.filename): \(.snippet)"')
EOF
        log "✅ ROAM tracker updated"
    fi
    
    # Step 8: Post task success to @claude-flow/cli
    npx @claude-flow/cli@latest hooks post-task \
        --task-id "portal-check-auto-$(date +%Y%m%d)" \
        --success true \
        --store-results true \
        >> "$LOG_FILE" 2>&1
    
    log "🎉 Portal check complete! $NEW_FINDINGS findings processed."
else
    log "✅ No new findings. Portal check complete."
fi

# Cleanup old logs (keep last 30 days)
find "$(dirname "$LOG_FILE")" -name "portal-check.log.*" -mtime +30 -delete 2>/dev/null || true

log "📊 Summary: Checked $LEGAL_FOLDER, found $NEW_FINDINGS new mentions"
