#!/usr/bin/env bash
#
# Credential Propagation Script
#
# PURPOSE: Find REAL API keys in environment and propagate to .env files
# SOLVES: User's question "how many scripts available to propagate correct env credentials?"
#
# FINDING REAL KEYS:
#   - Scans $HOME/.env, ~/.bashrc, ~/.zshrc, Keychain
#   - Detects: ANTHROPIC_API_KEY, AWS keys, HIVELOCITY_API_KEY, etc.
#   - Validates format (not placeholders like "your-key-here")
#
# PROPAGATING .env:
#   - Writes to agentic-flow/.env
#   - Copies to agentic-flow-core/.env
#   - Updates global config/.env
#   - Calls cpanel-env-setup.sh for final distribution
#
# Usage:
#   ./propagate-credentials.sh --scan      # Find all real keys
#   ./propagate-credentials.sh --propagate # Write to .env files
#   ./propagate-credentials.sh --validate  # Check which keys missing

set -euo pipefail

BASE_DIR="/Users/shahroozbhopti/Documents/code/investing/agentic-flow"
LOG_FILE="$HOME/Library/Logs/credential-propagation.log"

mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Function: Scan for real API keys in environment
scan_real_keys() {
    log "🔍 Scanning for REAL API keys (not placeholders)..."
    
    declare -A FOUND_KEYS
    
    # Check current environment
    for var in ANTHROPIC_API_KEY AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY HIVELOCITY_API_KEY \
               OPENAI_API_KEY GROQ_API_KEY COHERE_API_KEY PERPLEXITY_API_KEY \
               CLOUDFLARE_API_TOKEN POSTGRES_PASSWORD GITLAB_TOKEN PASSBOLT_API_TOKEN; do
        if [ -n "${!var:-}" ]; then
            local value="${!var}"
            # Skip placeholders
            if [[ ! "$value" =~ (your-|placeholder|changeme|xxx|yyy|zzz) ]]; then
                FOUND_KEYS["$var"]="$value"
                log "  ✅ Found: $var (${#value} chars)"
            fi
        fi
    done
    
    # Check ~/.env
    if [ -f "$HOME/.env" ]; then
        log "  📄 Scanning: $HOME/.env"
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            [[ "$key" =~ ^#.*$ ]] && continue
            [[ -z "$key" ]] && continue
            
            # Strip 'export ' prefix if present
            key="${key#export }"
            key="$(echo "$key" | xargs)"
            
            # Remove quotes from value
            value="${value%\"}"
            value="${value#\"}"
            value="${value%\'}"
            value="${value#\'}"
            
            # Skip placeholders and non-API vars
            if [[ ! "$value" =~ (your-|placeholder|changeme|xxx|yyy|zzz) ]] && [ -n "$value" ] && [[ "$key" =~ ^[A-Z_]+$ ]]; then
                FOUND_KEYS["$key"]="$value"
                log "  ✅ Found: $key (${#value} chars)"
            fi
        done < "$HOME/.env"
    fi
    
    # Check macOS Keychain for common items
    if command -v security &> /dev/null; then
        log "  🔐 Scanning: macOS Keychain"
        for service in anthropic-api hivelocity-api aws-credentials; do
            if security find-generic-password -s "$service" -w 2>/dev/null; then
                local key_value=$(security find-generic-password -s "$service" -w 2>/dev/null || echo "")
                if [ -n "$key_value" ]; then
                    FOUND_KEYS["${service^^}_KEY"]="$key_value"
                    log "  ✅ Found: ${service^^}_KEY from Keychain (${#key_value} chars)"
                fi
            fi
        done
    fi
    
    log ""
    log "📊 Summary: Found ${#FOUND_KEYS[@]} real API keys"
    
    # Export for use by other functions
    for key in "${!FOUND_KEYS[@]}"; do
        export "$key"="${FOUND_KEYS[$key]}"
    done
}

# Function: Propagate keys to .env files
propagate_to_env_files() {
    log "📝 Propagating keys to .env files..."
    
    # Target .env file
    local env_file="$BASE_DIR/.env"
    local backup_file="$env_file.backup.$(date +%Y%m%d-%H%M%S)"
    
    # Backup existing .env if exists
    if [ -f "$env_file" ]; then
        cp "$env_file" "$backup_file"
        log "  💾 Backup: $backup_file"
    fi
    
    # Create new .env with real keys
    log "  📄 Writing: $env_file"
    cat > "$env_file" << EOF
# Auto-generated by propagate-credentials.sh
# Generated: $(date)

# Anthropic
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

# AWS
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
AWS_REGION=${AWS_REGION:-us-west-1}

# Hivelocity
HIVELOCITY_API_KEY=${HIVELOCITY_API_KEY:-}

# PostgreSQL
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
DATABASE_URL=${DATABASE_URL:-}

# GitLab
GITLAB_TOKEN=${GITLAB_TOKEN:-}

# Passbolt
PASSBOLT_API_TOKEN=${PASSBOLT_API_TOKEN:-}

# Cloudflare
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL:-}

# OpenAI (if needed)
OPENAI_API_KEY=${OPENAI_API_KEY:-}

# Groq (fast LLM inference)
GROQ_API_KEY=${GROQ_API_KEY:-}

# Cohere (embeddings & reranking)
COHERE_API_KEY=${COHERE_API_KEY:-}

# Perplexity (search + LLM)
PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}

# Node environment
NODE_ENV=development
EOF
    
    log "  ✅ Created: $env_file"
    
    # Copy to agentic-flow-core/.env
    if [ -d "$BASE_DIR/agentic-flow-core" ]; then
        cp "$env_file" "$BASE_DIR/agentic-flow-core/.env"
        log "  ✅ Copied: agentic-flow-core/.env"
    fi
    
    # Copy to config/.env
    if [ -d "$BASE_DIR/config" ]; then
        cp "$env_file" "$BASE_DIR/config/.env"
        log "  ✅ Copied: config/.env"
    fi
    
    # Call cpanel-env-setup.sh if exists
    if [ -f "$BASE_DIR/scripts/cpanel-env-setup.sh" ]; then
        log "  🔧 Running: cpanel-env-setup.sh --all"
        bash "$BASE_DIR/scripts/cpanel-env-setup.sh" --all >> "$LOG_FILE" 2>&1 || true
        log "  ✅ cpanel-env-setup.sh complete"
    fi
}

# Function: Validate which keys are missing
validate_required_keys() {
    log "🔍 Validating required API keys..."
    
    local required_keys=(
        "ANTHROPIC_API_KEY"
        "OPENAI_API_KEY"
        "GROQ_API_KEY"
        "AWS_ACCESS_KEY_ID"
        "AWS_SECRET_ACCESS_KEY"
        "HIVELOCITY_API_KEY"
    )
    
    local missing_count=0
    local found_count=0
    
    for key in "${required_keys[@]}"; do
        if [ -n "${!key:-}" ] && [[ ! "${!key}" =~ (your-|placeholder|changeme) ]]; then
            log "  ✅ $key: FOUND (${#!key} chars)"
            found_count=$((found_count + 1))
        else
            log "  ❌ $key: MISSING or placeholder"
            missing_count=$((missing_count + 1))
        fi
    done
    
    log ""
    log "📊 Validation Summary:"
    log "  Found: $found_count / ${#required_keys[@]}"
    log "  Missing: $missing_count / ${#required_keys[@]}"
    
    if [ $missing_count -eq 0 ]; then
        log "  ✅ All required keys present!"
        return 0
    else
        log "  ⚠️ Some keys missing - check environment variables"
        return 1
    fi
}

# Function: Interactive key input
interactive_input() {
    log "🔑 Interactive key input..."
    
    echo ""
    echo "Enter API keys (or press Enter to skip):"
    echo ""
    
    read -p "ANTHROPIC_API_KEY: " anthropic_key
    [ -n "$anthropic_key" ] && export ANTHROPIC_API_KEY="$anthropic_key"
    
    read -p "AWS_ACCESS_KEY_ID: " aws_access
    [ -n "$aws_access" ] && export AWS_ACCESS_KEY_ID="$aws_access"
    
    read -p "AWS_SECRET_ACCESS_KEY: " aws_secret
    [ -n "$aws_secret" ] && export AWS_SECRET_ACCESS_KEY="$aws_secret"
    
    read -p "HIVELOCITY_API_KEY: " hivelocity_key
    [ -n "$hivelocity_key" ] && export HIVELOCITY_API_KEY="$hivelocity_key"
    
    log "  ✅ Keys entered"
}

# Main execution
case "${1:-help}" in
    --scan)
        scan_real_keys
        ;;
    
    --propagate)
        scan_real_keys
        propagate_to_env_files
        ;;
    
    --validate)
        scan_real_keys
        validate_required_keys
        ;;
    
    --interactive)
        interactive_input
        propagate_to_env_files
        ;;
    
    --help|*)
        log "📋 Usage:"
        log "  $0 --scan         # Find all real keys in environment"
        log "  $0 --propagate    # Scan and write to .env files"
        log "  $0 --validate     # Check which keys are missing"
        log "  $0 --interactive  # Enter keys manually"
        exit 1
        ;;
esac

log "🎉 Credential propagation complete!"
log "Log: $LOG_FILE"
