---
# Ansible Role: Syslog Client Handlers
# Off-Host Syslog Black Box Recorder

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
