import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';

test.describe('[FA] Native Capacitor Bridge Validation (Next Wave Network)', () => {
    
    // RED UNTIL *: The absolute proof of Native bridging is the injection of the Capacitor Core
    // SDK into the compiled distribution bundle for iOS and Android. If the `capacitor.js` bridge
    // is not physically present in the web assets delivered to the native container, the test STAYS RED.
    
    test('Capacitor native bridge layer is physically compiled into the iOS/Android distribution', async () => {
        const DOMAIN = 'nextwavenetwork';
        const APP_DIR = path.resolve(__dirname, `../../apps/${DOMAIN}`);
        
        // 1. App must exist (Generated by orchestrator)
        expect(fs.existsSync(APP_DIR), `App directory ${APP_DIR} does not exist.`).toBeTruthy();
        
        // 2. The Web distribution must contain the Capacitor Bridge Injector
        // Without this, the webview cannot communicate with iOS/Android native APIs (Camera, Push, etc)
        const distDir = path.join(APP_DIR, 'dist');
        expect(fs.existsSync(distDir), `Dist directory ${distDir} missing.`).toBeTruthy();
        
        // Ensure index.html imports capacitor.js or window.Capacitor is configured
        const indexPath = path.join(distDir, 'index.html');
        expect(fs.existsSync(indexPath), `index.html missing from dist.`).toBeTruthy();
        
        const htmlContent = fs.readFileSync(indexPath, 'utf-8');
        
        // The literal AST proof [FA]:
        const hasCapacitorBridge = htmlContent.includes('capacitor.js') || htmlContent.includes('window.Capacitor');
        
        expect(hasCapacitorBridge, 
            'FALSE GREEN PREVENTION: The index.html does not contain the native Capacitor Bridge. ' +
            'The app will run as a dumb webview without access to Next Wave Network native capabilities.'
        ).toBeTruthy();
    });
});
