apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing-sovereign

resources:
  - namespace.yaml
  - secrets-template.yaml
  - billing-api-deployment.yaml
  - billing-api-service.yaml
  - stripe-webhook-deployment.yaml
  - stripe-webhook-service.yaml
  - postgres-statefulset.yaml
  - ingress.yaml
