#!/bin/bash
# Immediate Action Items Execution Plan

echo "🚀 AISP Integration - Immediate Actions"
echo "========================================"
echo ""

# Block 1: Skills Extraction (P0)
echo "📦 Block 1: Skills Extraction"
timeout 60 npx agentdb learner run 1 0.0 0.0 false 2>&1 || echo "⚠️  AgentDB extraction timed out (may need manual intervention)"
echo ""

# Block 2: Coverage Baseline
echo "📊 Block 2: Coverage Baseline"
npm run test:jest -- --coverage --coverageDirectory=reports/coverage 2>&1 | tail -20
echo ""

# Block 3: TypeScript Errors
echo "🔍 Block 3: TypeScript Error Count"
npm run typecheck 2>&1 | tee reports/typescript-errors.txt | tail -10
echo "Total TS Errors: $(grep -c 'error TS' reports/typescript-errors.txt || echo 0)"
echo ""

# Block 4: ROAM Status
echo "📈 Block 4: ROAM Status Update"
if [ -f "./scripts/ay-yo-monitor-roam.sh" ]; then
  ./scripts/ay-yo-monitor-roam.sh > reports/roam-status-$(date +%Y%m%d).txt 2>&1
  echo "✅ ROAM status saved to reports/roam-status-*.txt"
else
  echo "⚠️  ROAM script not found"
fi
echo ""

# Block 5: Summary Report
echo "📋 Block 5: Generating Summary"
cat > reports/immediate-status-$(date +%Y%m%d).txt << REPORT
=== AISP Integration Status ===
Date: $(date)
Generated by: execution-plan.sh

Skills Extracted: $(npx agentdb stats 2>/dev/null | grep "Skills:" || echo "Unknown (check manually)")
Coverage: $(grep -A 1 "All files" reports/coverage/lcov-report/index.html 2>/dev/null | tail -1 || echo "Unknown (run npm run test:jest -- --coverage)")
TypeScript Errors: $(grep -c 'error TS' reports/typescript-errors.txt || echo "0")
Reports Generated: $(ls reports/ | wc -l) files

Next Steps:
1. Review reports/coverage/ for coverage details
2. Review reports/typescript-errors.txt for TS issues
3. Execute Phase 1: Create AISP type definitions
4. Run npm audit fix for security vulnerabilities
REPORT

cat reports/immediate-status-$(date +%Y%m%d).txt
echo ""
echo "✅ Execution plan complete! Check reports/ directory for details."
