/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single scored WSJF item exposed to JavaScript. */
export interface WsjfItemJs {
  id: string
  description: string
  businessValue: number
  timeCriticality: number
  riskReduction: number
  jobSize: number
  wsjfScore: number
  scoredAt: string
  justification?: string
  horizon?: string
}
/** Holding summary returned to JavaScript. */
export interface HoldingJs {
  assetName: string
  quantity: number
  costBasis: number
  currency: string
}
/** Rebalancing trade recommendation returned to JavaScript. */
export interface RebalanceTradeJs {
  assetName: string
  currentAllocationPct: number
  targetAllocationPct: number
  driftPct: number
  tradeValue: number
  tradeQuantity: number
  action: string
}
export interface EvidenceFile {
  path: string
  fileType: string
  sizeBytes: number
  isValid: boolean
  validationErrors: Array<string>
  metadata: Record<string, string>
}
export interface ExifData {
  dateTaken?: string
  cameraModel?: string
  gpsLatitude?: number
  gpsLongitude?: number
  hasTimestamp: boolean
  isAuthentic: boolean
}
export interface TimelineEntry {
  date: string
  eventType: string
  description: string
  evidenceFiles: Array<string>
  severity: string
}
export interface EvidenceValidationResult {
  totalFiles: number
  validFiles: number
  invalidFiles: number
  missingExif: number
  processingTimeMs: number
  files: Array<EvidenceFile>
  timeline: Array<TimelineEntry>
}
/** Systemic indifference score result for legal dispute assessment. */
export interface SystemicScoreJs {
  score: number
  maxScore: number
  verdict: string
}
/**
 * Calculate a systemic indifference score for a dispute.
 *
 * Scores range from 0-40. Verdicts:
 * - >30: "LitigationReady"
 * - >10: "SettlementOnly"
 * - ≤10: "Defer"
 *
 * @param score - Raw systemic score (0-40)
 * @returns SystemicScoreJs with verdict
 */
export declare function calculateSystemicScore(score: number): SystemicScoreJs
/**
 * Quick health check: returns a summary of the Rust domain model status.
 *
 * Useful for the TUI dashboard and CI/CD pipeline to verify the Rust layer
 * is compiled and operational without running the full test suite.
 *
 * @returns JSON string with module status counts
 */
export declare function domainHealthCheck(): string
export interface EvidenceMetadataJs {
  fileType: string
  dateTime?: string
  author?: string
  textContent?: string
  error?: string
}
export declare class WsjfCalculator {
  /**
   * Create a new WSJF calculator with default settings.
   *
   * Defaults: inputs bounded [1, 10], job_size floor = 1, staleness = 96h.
   */
  constructor()
  /**
   * Calculate WSJF score for a single item.
   *
   * All component values must be between 1 and 10 inclusive.
   * Extreme values (1 or 10) require a non-null `justification` string.
   *
   * @param id - Unique item identifier (e.g. "TASK-001")
   * @param description - Human-readable description
   * @param businessValue - Business value component [1-10]
   * @param timeCriticality - Time criticality component [1-10]
   * @param riskReduction - Risk reduction / opportunity enablement [1-10]
   * @param jobSize - Effort estimate [1-10]
   * @param justification - Required for extreme values (1 or 10)
   * @returns WsjfItemJs with calculated wsjfScore
   */
  calculate(id: string, description: string, businessValue: number, timeCriticality: number, riskReduction: number, jobSize: number, justification?: string | undefined | null): WsjfItemJs
  /**
   * Recalculate WSJF with time-decay applied to time_criticality.
   *
   * As a deadline approaches, TC increases linearly toward 10.
   *
   * @param item - Previously calculated WSJF item
   * @param elapsedFraction - 0.0 at scoring time, 1.0 at deadline
   * @returns Updated WsjfItemJs with decayed TC
   */
  withTimeDecay(item: WsjfItemJs, elapsedFraction: number): WsjfItemJs
  /**
   * Check if a WSJF item's score is stale (older than threshold, default 96h).
   *
   * @param scoredAt - ISO 8601 timestamp string from the item
   * @returns true if the score should be recalculated
   */
  isStale(scoredAt: string): boolean
  /**
   * Sort items by WSJF score descending (highest priority first).
   *
   * @param items - Array of WsjfItemJs objects
   * @returns Sorted array (new allocation; original not mutated)
   */
  prioritize(items: Array<WsjfItemJs>): Array<WsjfItemJs>
  /**
   * Detect anti-patterns in a scored backlog.
   *
   * Returns an array of warning strings. Empty array = no issues detected.
   * Warnings include: identical scores, job-size gaming, anchoring at max,
   * unjustified extremes, stale scores, score clustering.
   *
   * @param items - Array of WsjfItemJs objects to analyse
   * @returns Array of human-readable warning strings
   */
  detectAntiPatterns(items: Array<WsjfItemJs>): Array<string>
}
export declare class PortfolioManager {
  /**
   * Create a new portfolio with a name and base currency.
   *
   * @param name - Portfolio display name
   * @param baseCurrency - ISO currency code ("USD", "EUR", "GBP", "JPY", "BTC", "ETH")
   */
  constructor(name: string, baseCurrency: string)
  /** Get the portfolio UUID. */
  portfolioId(): string
  /** Get the portfolio name. */
  name(): string
  /** Get the number of holdings. */
  holdingCount(): number
  /**
   * Add an equity holding to the portfolio.
   *
   * @param ticker - Stock ticker symbol (e.g. "AAPL")
   * @param exchange - "NYSE", "NASDAQ", "LSE", "TSE", "COMEX"
   * @param sector - "Technology", "Healthcare", "Finance", "Energy", "ConsumerGoods", "Industrials"
   * @param marketCap - "Large", "Mid", "Small"
   * @param quantity - Number of shares (must be positive)
   * @param costBasis - Total cost basis in portfolio base currency
   */
  addEquity(ticker: string, exchange: string, sector: string, marketCap: string, quantity: number, costBasis: number): void
  /**
   * Add a cryptocurrency holding to the portfolio.
   *
   * @param symbol - Crypto symbol (e.g. "BTC", "ETH")
   * @param blockchain - "Bitcoin", "Ethereum", "Solana", "Polygon"
   * @param tokenType - "Coin", "Token", "NFT"
   * @param quantity - Amount (must be positive)
   * @param costBasis - Total cost basis in portfolio base currency
   */
  addCrypto(symbol: string, blockchain: string, tokenType: string, quantity: number, costBasis: number): void
  /**
   * List all holdings in the portfolio.
   *
   * @returns Array of HoldingJs objects
   */
  listHoldings(): Array<HoldingJs>
  /**
   * Calculate total portfolio value at given market prices.
   *
   * @param marketPrices - Object mapping asset name → price per unit (f64)
   * @returns Total value as f64
   */
  totalValue(marketPrices: Record<string, number>): number
  /**
   * Calculate total cost basis across all holdings.
   *
   * @returns Total cost basis as f64
   */
  totalCostBasis(): number
  /**
   * Calculate unrealised gain/loss.
   *
   * @param marketPrices - Object mapping asset name → price per unit
   * @returns Gain (positive) or loss (negative) as f64
   */
  unrealizedGain(marketPrices: Record<string, number>): number
  /**
   * Calculate return percentage.
   *
   * @param marketPrices - Object mapping asset name → price per unit
   * @returns Return as percentage (e.g. 25.0 for 25%)
   */
  returnPercentage(marketPrices: Record<string, number>): number
  /**
   * Calculate rebalancing trades to reach target allocations.
   *
   * @param targetAllocations - Object mapping asset name → target % (0-100)
   * @param marketPrices - Object mapping asset name → price per unit
   * @returns Array of RebalanceTradeJs recommendations sorted by absolute drift
   */
  rebalancingTrades(targetAllocations: Record<string, number>, marketPrices: Record<string, number>): Array<RebalanceTradeJs>
  /** Serialise the portfolio to a JSON string for persistence. */
  toJson(): string
}
export declare class PerformanceCalc {
  constructor()
  /**
   * Calculate Sharpe Ratio.
   *
   * @param returns - Array of periodic returns as decimals (e.g. 0.05 = 5%)
   * @param riskFreeRate - Risk-free rate for the same period
   * @returns Sharpe ratio (higher = better risk-adjusted return)
   */
  sharpeRatio(returns: Array<number>, riskFreeRate: number): number
  /**
   * Calculate maximum drawdown from a series of portfolio values.
   *
   * @param values - Array of portfolio values over time
   * @param currency - ISO currency code for the values
   * @returns Maximum drawdown as a decimal (e.g. 0.25 = 25% drawdown)
   */
  maxDrawdown(values: Array<number>, currency: string): number
  /**
   * Calculate Compound Annual Growth Rate (CAGR).
   *
   * @param initialValue - Starting portfolio value
   * @param finalValue - Ending portfolio value
   * @param years - Number of years (can be fractional, e.g. 1.5)
   * @param currency - ISO currency code
   * @returns CAGR as a decimal (e.g. 0.12 = 12% annual growth)
   */
  cagr(initialValue: number, finalValue: number, years: number, currency: string): number
  /**
   * Calculate simple total return.
   *
   * @param initialValue - Starting value
   * @param finalValue - Ending value
   * @param currency - ISO currency code
   * @returns Return as a decimal (e.g. 0.25 = 25%)
   */
  totalReturn(initialValue: number, finalValue: number, currency: string): number
  /**
   * Calculate arithmetic mean of a number series.
   *
   * @param values - Array of numbers
   * @returns Mean value
   */
  mean(values: Array<number>): number
  /**
   * Calculate sample standard deviation.
   *
   * @param values - Array of numbers (minimum 2)
   * @returns Standard deviation
   */
  stdDev(values: Array<number>): number
}
export declare class RiskAnalysis {
  constructor()
  /**
   * Calculate parametric Value at Risk.
   *
   * @param portfolioValue - Current total portfolio value
   * @param confidenceLevel - Confidence level (e.g. 0.95 for 95%)
   * @param dailyVolatility - Daily volatility (std dev of daily returns)
   * @param timeHorizonDays - Number of days for VaR horizon
   * @param currency - ISO currency code
   * @returns Maximum expected loss at the given confidence level
   */
  valueAtRisk(portfolioValue: number, confidenceLevel: number, dailyVolatility: number, timeHorizonDays: number, currency: string): number
  /**
   * Calculate portfolio volatility from periodic returns.
   *
   * @param returns - Array of periodic returns (e.g. daily returns)
   * @returns Volatility (sample standard deviation)
   */
  volatility(returns: Array<number>): number
  /**
   * Calculate annualised volatility from daily returns.
   *
   * Assumes 252 trading days per year.
   *
   * @param dailyReturns - Array of daily returns
   * @returns Annualised volatility
   */
  annualisedVolatility(dailyReturns: Array<number>): number
  /**
   * Calculate portfolio beta relative to market benchmark.
   *
   * @param portfolioReturns - Array of portfolio periodic returns
   * @param marketReturns - Array of market benchmark returns (same period, same length)
   * @returns Beta coefficient (1.0 = market, >1 = more volatile, <1 = less volatile)
   */
  beta(portfolioReturns: Array<number>, marketReturns: Array<number>): number
  /**
   * Calculate Pearson correlation between two return series.
   *
   * @param seriesA - First return series
   * @param seriesB - Second return series (same length)
   * @returns Correlation coefficient (-1.0 to 1.0)
   */
  correlation(seriesA: Array<number>, seriesB: Array<number>): number
}
export declare class Cache {
  /**
   * Create a new LRU cache with the given capacity.
   *
   * @param capacity - Maximum number of entries. 0 = disabled (no-op cache).
   */
  constructor(capacity: number)
  /** Get the maximum capacity. */
  capacity(): number
  /**
   * Store a key-value pair. Evicts LRU entry if at capacity.
   *
   * @param key - Cache key
   * @param value - Value to store (JSON string for complex objects)
   */
  put(key: string, value: string): Promise<void>
  /**
   * Retrieve a value by key. Promotes key to most-recently-used.
   *
   * @param key - Cache key
   * @returns Value string, or null if not found / evicted
   */
  get(key: string): Promise<string | null>
  /**
   * Check if a key exists without promoting it (peek operation).
   *
   * @param key - Cache key
   * @returns true if key is in cache
   */
  contains(key: string): Promise<boolean>
  /**
   * Remove a specific key from the cache.
   *
   * @param key - Cache key to remove
   * @returns The removed value, or null if not present
   */
  remove(key: string): Promise<string | null>
  /** Remove all entries from the cache. */
  clear(): Promise<void>
  /** Check if the cache is empty. */
  isEmpty(): Promise<boolean>
  /** Get the current number of entries. */
  len(): Promise<number>
  /**
   * Get all keys in LRU order (least recently used first).
   *
   * Useful for debugging and cache inspection.
   */
  keysLruOrder(): Promise<Array<string>>
  /**
   * Serialise the cache to a JSON string for persistence.
   *
   * Captures both data and LRU ordering so `restore` can reconstruct exactly.
   */
  snapshot(): Promise<string>
  /**
   * Restore a cache from a JSON snapshot.
   *
   * @param json - JSON string from a previous `snapshot()` call
   * @param capacity - Maximum capacity for the restored cache
   * @returns New Cache instance with restored data and LRU order
   */
  static restore(json: string, capacity: number): Cache
}
export declare class EvidenceValidator {
  /**
   * Create new evidence validator
   *
   * @param basePath - Base directory for evidence bundle
   */
  constructor(basePath: string)
  /**
   * Validate all evidence files in directory
   *
   * Fast Rust implementation processes 40+ files in <5s
   * Validates: PDFs (text extraction), photos (EXIF), work orders
   *
   * @param directory - Subdirectory to scan (e.g. "05_HABITABILITY_EVIDENCE")
   * @returns Validation result with detailed file-by-file analysis
   */
  validateDirectory(directory: string): Promise<EvidenceValidationResult>
  /**
   * Validate single evidence file
   *
   * @param filePath - Path to file
   * @returns EvidenceFile with validation results
   */
  validateFile(filePathStr: string): Promise<EvidenceFile>
  /**
   * Extract EXIF data from photo
   *
   * @param filePath - Path to image file
   * @returns EXIF data with timestamp validation
   */
  extractExif(filePathStr: string): Promise<ExifData>
  /**
   * Quick stats for evidence bundle health
   *
   * @returns JSON string with summary statistics
   */
  bundleHealthCheck(): Promise<string>
}
export declare class EvidenceProcessor {
  constructor()
  /**
   * Extract metadata and text from a file (PDF, JPEG, etc.)
   *
   * @param file_path - Path to the file
   * @returns EvidenceMetadataJs object
   */
  extractMetadata(filePath: string): EvidenceMetadataJs
}
