---
# =============================================================================
# Base Role - Handlers
# =============================================================================

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: reload ufw
  community.general.ufw:
    state: reloaded
