#!/bin/bash
# bundle-evidence.sh - 7-section evidence bundler with SHA-256 chain of custody
# Generates ZIP package with court docs, correspondence, lease, regulatory, index, custody log

# CRITICAL FIX (QE Review): Remove -e to prevent immediate exit on error
set -uo pipefail

# Configuration
CASE_NUMBER="${1:-26CV005596-590}"
OUTPUT_DIR="${2:-$HOME/Downloads}"
CASE_DIR="${CASE_DIR:-$HOME/Documents/Personal/CLT/MAA/Uptown/BHOPTI-LEGAL/01-ACTIVE-CRITICAL/MAA-${CASE_NUMBER}}"
BUNDLE_DIR="${CASE_DIR}/EVIDENCE_BUNDLE"
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
BUNDLE_NAME="MAA_${CASE_NUMBER}_Evidence_${TIMESTAMP}"
ERROR_LOG="${CASE_DIR}/../../logs/errors.log"

# Evidence sections
SECTIONS=(
    "01_COURT_DOCUMENTS"
    "02_CORRESPONDENCE"
    "03_LEASE_AGREEMENTS"
    "04_REGULATORY_FILINGS"
    "05_HABITABILITY_EVIDENCE"
    "06_FINANCIAL_RECORDS"
    "07_CHAIN_OF_CUSTODY"
)

# Ensure error log directory exists
mkdir -p "$(dirname "${ERROR_LOG}")"

# Function: Log with timestamp
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

# CRITICAL FIX (QE Review): Add error logging function
log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" | tee -a "${ERROR_LOG}"
}

# Function: Calculate SHA-256 hash
calculate_hash() {
    local file="$1"
    shasum -a 256 "${file}" | awk '{print $1}'
}

# Function: Create bundle directory structure
create_bundle_structure() {
    log "Creating bundle structure: ${BUNDLE_DIR}"
    
    mkdir -p "${BUNDLE_DIR}"
    
    for section in "${SECTIONS[@]}"; do
        mkdir -p "${BUNDLE_DIR}/${section}"
    done
}

# Function: Copy evidence files
copy_evidence_files() {
    log "Copying evidence files..."
    
    # Court documents
    if [[ -d "${CASE_DIR}/COURT_FILINGS" ]]; then
        cp -r "${CASE_DIR}/COURT_FILINGS/"* "${BUNDLE_DIR}/01_COURT_DOCUMENTS/" 2>/dev/null || true
    fi
    
    # Correspondence
    if [[ -d "${CASE_DIR}/CORRESPONDENCE" ]]; then
        cp -r "${CASE_DIR}/CORRESPONDENCE/"* "${BUNDLE_DIR}/02_CORRESPONDENCE/" 2>/dev/null || true
    fi
    
    # Lease agreements
    if [[ -d "${CASE_DIR}/LEASE" ]]; then
        cp -r "${CASE_DIR}/LEASE/"* "${BUNDLE_DIR}/03_LEASE_AGREEMENTS/" 2>/dev/null || true
    fi
    
    # Regulatory filings
    if [[ -d "${CASE_DIR}/REGULATORY" ]]; then
        cp -r "${CASE_DIR}/REGULATORY/"* "${BUNDLE_DIR}/04_REGULATORY_FILINGS/" 2>/dev/null || true
    fi
    
    # Habitability evidence
    if [[ -d "${CASE_DIR}/HABITABILITY" ]]; then
        cp -r "${CASE_DIR}/HABITABILITY/"* "${BUNDLE_DIR}/05_HABITABILITY_EVIDENCE/" 2>/dev/null || true
    fi
    
    # Financial records
    if [[ -d "${CASE_DIR}/FINANCIAL" ]]; then
        cp -r "${CASE_DIR}/FINANCIAL/"* "${BUNDLE_DIR}/06_FINANCIAL_RECORDS/" 2>/dev/null || true
    fi
}

# Function: Generate chain of custody
generate_chain_of_custody() {
    log "Generating chain of custody..."
    
    local custody_file="${BUNDLE_DIR}/07_CHAIN_OF_CUSTODY/CHAIN_OF_CUSTODY.txt"
    
    cat > "${custody_file}" <<EOF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  CHAIN OF CUSTODY LOG
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Case Number: ${CASE_NUMBER}
Bundle Generated: $(date '+%Y-%m-%d %H:%M:%S')
Generated By: $(whoami)@$(hostname)
Bundle Name: ${BUNDLE_NAME}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  FILE HASHES (SHA-256)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF
    
    # Calculate hashes for all files
    local total_files=0
    local total_size=0
    
    for section in "${SECTIONS[@]}"; do
        if [[ "${section}" == "07_CHAIN_OF_CUSTODY" ]]; then
            continue
        fi
        
        echo "" >> "${custody_file}"
        echo "Section: ${section}" >> "${custody_file}"
        echo "----------------------------------------" >> "${custody_file}"
        
        if [[ -d "${BUNDLE_DIR}/${section}" ]]; then
            find "${BUNDLE_DIR}/${section}" -type f | while read -r file; do
                local hash=$(calculate_hash "${file}")
                local size=$(stat -f%z "${file}" 2>/dev/null || stat -c%s "${file}" 2>/dev/null)
                local rel_path="${file#${BUNDLE_DIR}/}"
                
                echo "${hash}  ${rel_path} (${size} bytes)" >> "${custody_file}"
                
                total_files=$((total_files + 1))
                total_size=$((total_size + size))
            done
        fi
    done
    
    # Summary
    cat >> "${custody_file}" <<EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Files: ${total_files}
Total Size: ${total_size} bytes ($(numfmt --to=iec-i --suffix=B ${total_size} 2>/dev/null || echo "${total_size} bytes"))

Verification:
  To verify integrity, run:
  shasum -a 256 -c CHAIN_OF_CUSTODY.txt

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
    
    log "Chain of custody generated: ${custody_file}"
}

# Function: Generate index
generate_index() {
    log "Generating index..."
    
    local index_file="${BUNDLE_DIR}/INDEX.txt"
    
    cat > "${index_file}" <<EOF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  EVIDENCE BUNDLE INDEX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Case Number: ${CASE_NUMBER}
Bundle Name: ${BUNDLE_NAME}
Generated: $(date '+%Y-%m-%d %H:%M:%S')

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  SECTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF
    
    for section in "${SECTIONS[@]}"; do
        echo "" >> "${index_file}"
        echo "${section}" >> "${index_file}"
        echo "----------------------------------------" >> "${index_file}"
        
        if [[ -d "${BUNDLE_DIR}/${section}" ]]; then
            find "${BUNDLE_DIR}/${section}" -type f | sed "s|${BUNDLE_DIR}/${section}/|  - |" >> "${index_file}"
        else
            echo "  (empty)" >> "${index_file}"
        fi
    done
    
    log "Index generated: ${index_file}"
}

# Function: Create ZIP bundle
create_zip_bundle() {
    log "Creating ZIP bundle..."
    
    local zip_file="${OUTPUT_DIR}/${BUNDLE_NAME}.zip"
    
    cd "${BUNDLE_DIR}/.."
    zip -r "${zip_file}" "$(basename "${BUNDLE_DIR}")" > /dev/null
    
    local bundle_hash=$(calculate_hash "${zip_file}")
    
    log "Bundle created: ${zip_file}"
    log "Bundle hash: ${bundle_hash}"
    log "Bundle size: $(ls -lh "${zip_file}" | awk '{print $5}')"
}

# Main execution
main() {
    log "Starting evidence bundle generation for case ${CASE_NUMBER}"
    
    create_bundle_structure
    copy_evidence_files
    generate_chain_of_custody
    generate_index
    create_zip_bundle
    
    log "✅ Evidence bundle complete"
}

# Run main function
main

