/**
 * Shareable Outputs System
 *
 * System for creating, managing, and exporting shareable outputs from IDE integrations
 */

import { EventEmitter } from 'events';
import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';
import {
  ShareableOutput
} from './types';

export class ShareableOutputsSystem extends EventEmitter {
  private outputs: Map<string, ShareableOutput> = new Map();
  private outputDirectory: string;

  constructor(outputDirectory: string = './shareable-outputs') {
    super();
    this.outputDirectory = outputDirectory;
  }

  createOutput(output: Omit<ShareableOutput, 'id' | 'createdAt'>): ShareableOutput {
    const fullOutput: ShareableOutput = {
      ...output,
      id: `output-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      createdAt: new Date()
    };

    this.outputs.set(fullOutput.id, fullOutput);
    this.emit('output-created', fullOutput);

    return fullOutput;
  }

  async exportOutput(outputId: string, format?: 'json' | 'html' | 'pdf' | 'markdown'): Promise<string> {
    const output = this.outputs.get(outputId);
    if (!output) {
      throw new Error(`Output not found: ${outputId}`);
    }

    const exportFormat = format || output.format;
    const fileName = `${output.id}.${exportFormat}`;
    const filePath = join(this.outputDirectory, fileName);

    let content: string;

    switch (exportFormat) {
      case 'json':
        content = JSON.stringify(output, null, 2);
        break;
      case 'html':
        content = this.generateHTML(output);
        break;
      case 'markdown':
        content = this.generateMarkdown(output);
        break;
      case 'pdf':
        // In a real implementation, this would use a PDF generation library
        content = JSON.stringify(output); // Placeholder
        break;
      default:
        content = JSON.stringify(output);
    }

    await writeFile(filePath, content, 'utf-8');

    const shareableUrl = `/shareable-outputs/${fileName}`;
    this.emit('output-exported', { output, format: exportFormat, url: shareableUrl });

    return shareableUrl;
  }

  private generateHTML(output: ShareableOutput): string {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${output.title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .metadata { background: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .content { line-height: 1.6; }
        pre { background: #f8f8f8; padding: 15px; border-radius: 5px; overflow-x: auto; }
        .footer { margin-top: 40px; font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${output.title}</h1>
        <p>${output.description}</p>
    </div>

    <div class="metadata">
        <strong>Type:</strong> ${output.type}<br>
        <strong>Created:</strong> ${output.createdAt.toISOString()}<br>
        <strong>Access Level:</strong> ${output.accessLevel}<br>
        ${output.expiresAt ? `<strong>Expires:</strong> ${output.expiresAt.toISOString()}<br>` : ''}
    </div>

    <div class="content">
        <h2>Content</h2>
        ${this.formatContent(output.data, output.format)}
    </div>

    <div class="footer">
        <p>Generated by Agentic Flow IDE Integration System</p>
    </div>
</body>
</html>`;
  }

  private generateMarkdown(output: ShareableOutput): string {
    return `# ${output.title}

${output.description}

## Metadata

- **Type**: ${output.type}
- **Created**: ${output.createdAt.toISOString()}
- **Access Level**: ${output.accessLevel}
${output.expiresAt ? `- **Expires**: ${output.expiresAt.toISOString()}` : ''}

## Content

${this.formatContentAsMarkdown(output.data, output.format)}

---

*Generated by Agentic Flow IDE Integration System*`;
  }

  private formatContent(data: any, format: string): string {
    if (format === 'json') {
      return `<pre>${JSON.stringify(data, null, 2)}</pre>`;
    }

    if (typeof data === 'object') {
      return `<pre>${JSON.stringify(data, null, 2)}</pre>`;
    }

    return `<p>${String(data)}</p>`;
  }

  private formatContentAsMarkdown(data: any, format: string): string {
    if (format === 'json') {
      return `\`\`\`json\n${JSON.stringify(data, null, 2)}\n\`\`\``;
    }

    if (typeof data === 'object') {
      return `\`\`\`json\n${JSON.stringify(data, null, 2)}\n\`\`\``;
    }

    return String(data);
  }

  async importOutput(filePath: string): Promise<ShareableOutput> {
    const content = await readFile(filePath, 'utf-8');
    const output: ShareableOutput = JSON.parse(content);

    // Validate the imported output
    if (!output.id || !output.title || !output.createdAt) {
      throw new Error('Invalid output format');
    }

    this.outputs.set(output.id, output);
    this.emit('output-imported', output);

    return output;
  }

  getOutput(outputId: string): ShareableOutput | undefined {
    return this.outputs.get(outputId);
  }

  getOutputsByType(type: ShareableOutput['type']): ShareableOutput[] {
    return Array.from(this.outputs.values())
      .filter(output => output.type === type);
  }

  getOutputsByAccessLevel(accessLevel: ShareableOutput['accessLevel']): ShareableOutput[] {
    return Array.from(this.outputs.values())
      .filter(output => output.accessLevel === accessLevel);
  }

  updateOutput(outputId: string, updates: Partial<ShareableOutput>): ShareableOutput | null {
    const output = this.outputs.get(outputId);
    if (!output) return null;

    Object.assign(output, updates);
    this.emit('output-updated', output);

    return output;
  }

  deleteOutput(outputId: string): boolean {
    const output = this.outputs.get(outputId);
    if (!output) return false;

    this.outputs.delete(outputId);
    this.emit('output-deleted', output);

    return true;
  }

  getAllOutputs(): ShareableOutput[] {
    return Array.from(this.outputs.values());
  }

  async generateDashboardReport(dashboardId: string): Promise<ShareableOutput> {
    // Mock dashboard report generation
    const reportData = {
      dashboardId,
      metrics: {
        totalViews: Math.floor(Math.random() * 1000),
        activeUsers: Math.floor(Math.random() * 100),
        avgLoadTime: Math.random() * 2000 + 500,
        uptime: Math.random() * 0.1 + 0.95
      },
      widgets: [
        { id: 'metric-1', type: 'chart', views: Math.floor(Math.random() * 500) },
        { id: 'metric-2', type: 'table', views: Math.floor(Math.random() * 300) },
        { id: 'metric-3', type: 'text', views: Math.floor(Math.random() * 200) }
      ],
      generatedAt: new Date().toISOString()
    };

    return this.createOutput({
      title: `Dashboard Report - ${dashboardId}`,
      description: `Performance and usage report for dashboard ${dashboardId}`,
      type: 'report',
      format: 'json',
      data: reportData,
      metadata: {
        source: 'dashboard-integration',
        dashboardId,
        reportType: 'performance'
      },
      accessLevel: 'team'
    });
  }

  async generateSimulationReport(simulationId: string): Promise<ShareableOutput> {
    // Mock simulation report generation
    const reportData = {
      simulationId,
      summary: {
        totalScenarios: Math.floor(Math.random() * 10) + 5,
        completedScenarios: Math.floor(Math.random() * 8) + 3,
        avgConfidence: Math.random() * 0.3 + 0.7,
        executionTime: Math.random() * 5000 + 1000
      },
      results: Array.from({ length: 5 }, (_, i) => ({
        scenarioId: `scenario-${i + 1}`,
        confidence: Math.random() * 0.4 + 0.6,
        executionTime: Math.random() * 1000 + 200,
        success: Math.random() > 0.2
      })),
      recommendations: [
        'Consider optimizing input parameters',
        'Review high-confidence scenarios for implementation',
        'Validate results with domain experts'
      ],
      generatedAt: new Date().toISOString()
    };

    return this.createOutput({
      title: `Simulation Report - ${simulationId}`,
      description: `Detailed results and analysis for simulation ${simulationId}`,
      type: 'simulation',
      format: 'json',
      data: reportData,
      metadata: {
        source: 'predictive-simulator',
        simulationId,
        reportType: 'results'
      },
      accessLevel: 'organization'
    });
  }

  async cleanupExpiredOutputs(): Promise<number> {
    const now = new Date();
    let deletedCount = 0;

    for (const [id, output] of this.outputs) {
      if (output.expiresAt && output.expiresAt < now) {
        this.outputs.delete(id);
        deletedCount++;
        this.emit('output-expired', output);
      }
    }

    return deletedCount;
  }

  async healthCheck(): Promise<Record<string, any>> {
    const totalOutputs = this.outputs.size;
    const expiredOutputs = Array.from(this.outputs.values())
      .filter(o => o.expiresAt && o.expiresAt < new Date()).length;

    return {
      totalOutputs,
      expiredOutputs,
      outputsByType: this.getOutputsByType('dashboard').length,
      outputsByAccessLevel: {
        private: this.getOutputsByAccessLevel('private').length,
        team: this.getOutputsByAccessLevel('team').length,
        organization: this.getOutputsByAccessLevel('organization').length,
        public: this.getOutputsByAccessLevel('public').length
      },
      outputDirectory: this.outputDirectory
    };
  }
}