version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:18.6.1-ee.0'
    restart: always
    container_name: gitlab-web-1
    hostname: 'git.tag.ooo'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.tag.ooo'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        puma['worker_processes'] = 4
        sidekiq['max_concurrency'] = 10
    ports:
      - '8080:80'
      - '8443:443'
      - '2224:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
      - 'gitlab_backups:/var/opt/gitlab/backups'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    shm_size: '256m'

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_backups:
