version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:18.0.0-ee.0'
    restart: always
    hostname: 'gitlab.tag.ooo'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.tag.ooo'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
      - '/data/gitlab/backups:/var/opt/gitlab/backups'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    shm_size: '256m'
