import axios from 'axios';
import * as fs from 'fs';
import * as path from 'path';

interface SimplifyJob {
  id: string;
  title: string;
  company: string;
  location: string;
  url: string;
  posted_date: string;
  description: string;
  commitment?: string; // "Full-time", "Contract", "Consulting"
}

interface ApplicationTracker {
  applications: Application[];
}

interface Application {
  id: string;
  company: string;
  role: string;
  apply_url: string;
  applied_date: string;
  status: 'pending' | 'submitted' | 'interview' | 'offer' | 'rejected';
  cover_letter: string;
  notes: string;
}

const CONFIG_PATH = path.join(__dirname, '../../config.json');
const TRACKER_PATH = path.join(process.env.HOME!, 'Documents/Personal/CLT/MAA/applications.json');

async function scrapeSimplifyJobs(): Promise<SimplifyJob[]> {
  try {
    // Simplify.jobs API endpoint (hypothetical - needs actual API key)
    const response = await axios.get('https://api.simplify.jobs/v1/jobs', {
      params: {
        keywords: 'consulting OR attorney OR coach',
        commitment: 'contract,part-time',
        limit: 50
      },
      headers: {
        'Authorization': `Bearer ${process.env.SIMPLIFY_API_KEY || 'demo-key'}`,
        'User-Agent': 'ReverseRecruiter/1.0'
      }
    });

    return response.data.jobs || [];
  } catch (error) {
    console.error('[ERROR] Simplify.jobs API failed:', error);
    // Fallback to mock data for testing
    return mockJobs();
  }
}

function mockJobs(): SimplifyJob[] {
  return [
    {
      id: 'job-1',
      title: 'Agentic Coach (250h Consulting)',
      company: '720.chat',
      location: 'Remote',
      url: 'https://720.chat/careers',
      posted_date: '2026-03-01',
      description: 'Seeking experienced Agile coach with data analytics background',
      commitment: 'Contract'
    },
    {
      id: 'job-2',
      title: 'Associate Attorney (Pro Se Support)',
      company: 'TAG.VOTE',
      location: 'Remote',
      url: 'mailto:agentic.coach@TAG.VOTE',
      posted_date: '2026-03-02',
      description: 'Legal research and trial preparation assistance',
      commitment: 'Contract'
    },
    {
      id: 'job-3',
      title: 'Data Analyst (Contract)',
      company: 'O-GOV.com',
      location: 'Charlotte, NC',
      url: 'https://o-gov.com/careers',
      posted_date: '2026-02-28',
      description: 'Government data analytics and visualization',
      commitment: 'Contract'
    }
  ];
}

function filterFor250hRoles(jobs: SimplifyJob[]): SimplifyJob[] {
  const keywords = ['contract', 'consulting', '250', 'part-time', 'attorney', 'coach'];
  return jobs.filter(job => {
    const text = `${job.title} ${job.description} ${job.commitment}`.toLowerCase();
    return keywords.some(kw => text.includes(kw));
  });
}

async function loadOrCreateTracker(): Promise<ApplicationTracker> {
  try {
    if (fs.existsSync(TRACKER_PATH)) {
      const data = fs.readFileSync(TRACKER_PATH, 'utf-8');
      return JSON.parse(data);
    }
  } catch (error) {
    console.warn('[WARN] Could not load tracker, creating new:', error);
  }
  return { applications: [] };
}

async function saveTracker(tracker: ApplicationTracker): Promise<void> {
  const dir = path.dirname(TRACKER_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(TRACKER_PATH, JSON.stringify(tracker, null, 2));
  console.log(`[INFO] Tracker saved: ${tracker.applications.length} applications`);
}

export async function runScraper(): Promise<Application[]> {
  console.log('[INFO] Starting Simplify.jobs scraper...');
  
  const allJobs = await scrapeSimplifyJobs();
  console.log(`[INFO] Found ${allJobs.length} jobs`);
  
  const filteredJobs = filterFor250hRoles(allJobs);
  console.log(`[INFO] Filtered to ${filteredJobs.length} 250h consulting roles`);
  
  const tracker = await loadOrCreateTracker();
  const newApplications: Application[] = [];
  
  for (const job of filteredJobs) {
    // Check if already applied
    const existing = tracker.applications.find(app => app.company === job.company && app.role === job.title);
    if (existing) {
      console.log(`[SKIP] Already applied: ${job.company} - ${job.title}`);
      continue;
    }
    
    // Create new application entry
    const application: Application = {
      id: `app-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      company: job.company,
      role: job.title,
      apply_url: job.url,
      applied_date: new Date().toISOString(),
      status: 'pending',
      cover_letter: '', // Will be generated by application-writer agent
      notes: `Scraped from Simplify.jobs on ${new Date().toLocaleDateString()}`
    };
    
    newApplications.push(application);
    tracker.applications.push(application);
  }
  
  await saveTracker(tracker);
  console.log(`[OK] Scraped ${newApplications.length} new applications`);
  
  return newApplications;
}

if (require.main === module) {
  runScraper().catch(err => {
    console.error('[FATAL]', err);
    process.exit(1);
  });
}
