/**
 * Economic Metrics Integration System for Pattern Events
 *
 * Provides comprehensive economic analysis including:
 * - Cost of Delay (COD) calculations with pattern-specific formulas
 * - Weighted Shortest Job First (WSJF) scoring with business value correlation
 * - ROI tracking and trend analysis
 * - Economic impact assessment across governance circles
 * - Business value correlation with pattern execution
 */

import type { PatternEvent } from './shared_utils.js';

// Enhanced Economic Data Interface
export interface EnhancedEconomicData {
  /** Basic Cost of Delay */
  cod: number;
  /** WSJF score */
  wsjf_score: number;
  /** Risk-adjusted Cost of Delay */
  risk_adjusted_cod: number;
  /** Time-criticality multiplier */
  time_criticality_factor: number;
  /** Business impact score (1-100) */
  business_impact: number;
  /** User value score (1-100) */
  user_value: number;
  /** Risk reduction value (1-100) */
  risk_reduction_value: number;
  /** Estimated implementation cost */
  implementation_cost: number;
  /** Expected duration (hours) */
  duration: number;
  /** ROI calculation */
  roi: number;
  /** Net present value */
  npv: number;
  /** Economic trend data */
  economic_trend: EconomicTrend;
  /** Circle-specific economic impact */
  circle_impact: CircleEconomicImpact;
  /** Pattern category economic data */
  category_economics: CategoryEconomics;
  /** Business value correlation */
  business_correlation: BusinessValueCorrelation;
}

export interface EconomicTrend {
  /** Historical COD trend */
  cod_trend: 'increasing' | 'decreasing' | 'stable';
  /** Trend percentage */
  trend_percentage: number;
  /** Forecasted COD for next period */
  forecasted_cod: number;
  /** Confidence interval */
  confidence_interval: [number, number];
  /** Economic velocity (COD/time unit) */
  economic_velocity: number;
}

export interface CircleEconomicImpact {
  /** Circle name */
  circle: string;
  /** Economic contribution by this circle */
  economic_contribution: number;
  /** Risk exposure for this circle */
  risk_exposure: number;
  /** Value generated by patterns in this circle */
  value_generated: number;
  /** Cost incurred by this circle */
  cost_incurred: number;
  /** Economic efficiency ratio */
  efficiency_ratio: number;
}

export interface CategoryEconomics {
  /** Pattern category */
  category: string;
  /** Category-specific COD multiplier */
  cod_multiplier: number;
  /** Average implementation cost */
  avg_implementation_cost: number;
  /** Success rate by category */
  success_rate: number;
  /** Economic value distribution */
  value_distribution: {
    low: number;    // 0-33rd percentile
    medium: number; // 34-67th percentile
    high: number;   // 68-100th percentile
  };
}

export interface BusinessValueCorrelation {
  /** Business objectives affected */
  objectives_affected: string[];
  /** KPI impact scores */
  kpi_impact: Record<string, number>;
  /** Stakeholder value mapping */
  stakeholder_value: Record<string, number>;
  /** Market impact assessment */
  market_impact: number;
  /** Customer value score */
  customer_value: number;
  /** Competitive advantage score */
  competitive_advantage: number;
}

export interface ROIMetrics {
  /** Initial investment */
  initial_investment: number;
  /** Returns over time period */
  returns: number[];
  /** Time periods (hours/days/weeks) */
  time_periods: string[];
  /** Cumulative ROI */
  cumulative_roi: number;
  /** Payback period */
  payback_period: number;
  /** ROI rate (percentage) */
  roi_rate: number;
  /** Risk-adjusted ROI */
  risk_adjusted_roi: number;
}

export interface EconomicParameters {
  /** Discount rate for NPV calculations */
  discount_rate: number;
  /** Risk-free rate */
  risk_free_rate: number;
  /** Market risk premium */
  market_risk_premium: number;
  /** Economic time horizon (days) */
  time_horizon: number;
  /** Inflation rate */
  inflation_rate: number;
  /** Opportunity cost rate */
  opportunity_cost_rate: number;
}

/**
 * Economic Metrics Calculator
 */
export class EconomicMetricsCalculator {
  private readonly DEFAULT_PARAMETERS: EconomicParameters = {
    discount_rate: 0.08,           // 8% annual discount rate
    risk_free_rate: 0.02,          // 2% risk-free rate
    market_risk_premium: 0.06,     // 6% market risk premium
    time_horizon: 90,              // 90-day horizon
    inflation_rate: 0.025,         // 2.5% inflation
    opportunity_cost_rate: 0.10    // 10% opportunity cost
  };

  private readonly CATEGORY_ECONOMICS: Record<string, CategoryEconomics> = {
    'ML': {
      category: 'ML',
      cod_multiplier: 1.3,
      avg_implementation_cost: 50,
      success_rate: 0.75,
      value_distribution: { low: 10, medium: 25, high: 60 }
    },
    'HPC': {
      category: 'HPC',
      cod_multiplier: 1.2,
      avg_implementation_cost: 40,
      success_rate: 0.85,
      value_distribution: { low: 15, medium: 30, high: 55 }
    },
    'Stats': {
      category: 'Stats',
      cod_multiplier: 0.9,
      avg_implementation_cost: 25,
      success_rate: 0.90,
      value_distribution: { low: 20, medium: 35, high: 45 }
    },
    'Device/Web': {
      category: 'Device/Web',
      cod_multiplier: 1.0,
      avg_implementation_cost: 30,
      success_rate: 0.80,
      value_distribution: { low: 25, medium: 40, high: 35 }
    },
    'General': {
      category: 'General',
      cod_multiplier: 0.8,
      avg_implementation_cost: 20,
      success_rate: 0.85,
      value_distribution: { low: 30, medium: 45, high: 25 }
    }
  };

  private readonly CIRCLE_ECONOMIC_PROFILES: Record<string, Partial<CircleEconomicImpact>> = {
    'governance': { economic_contribution: 0.8, risk_exposure: 0.6 },
    'analyst': { economic_contribution: 0.9, risk_exposure: 0.4 },
    'assessor': { economic_contribution: 0.7, risk_exposure: 0.5 },
    'innovator': { economic_contribution: 1.2, risk_exposure: 0.8 },
    'intuitive': { economic_contribution: 0.6, risk_exposure: 0.3 },
    'orchestrator': { economic_contribution: 1.0, risk_exposure: 0.7 },
    'seeker': { economic_contribution: 0.5, risk_exposure: 0.2 },
    'retro': { economic_contribution: 0.4, risk_exposure: 0.1 }
  };

  constructor(
    private historicalData: PatternEvent[] = [],
    private parameters: EconomicParameters = {} as EconomicParameters
  ) {
    // Apply default parameters
    this.parameters = { ...this.DEFAULT_PARAMETERS, ...parameters };
  }

  /**
   * Calculate comprehensive economic metrics for a pattern event
   */
  public calculateEconomicMetrics(event: PatternEvent): EnhancedEconomicData {
    const baseCOD = this.calculateBaseCOD(event);
    const riskAdjustedCOD = this.calculateRiskAdjustedCOD(event, baseCOD);
    const timeCriticality = this.calculateTimeCriticality(event);
    const businessImpact = this.calculateBusinessImpact(event);
    const userValue = this.calculateUserValue(event);
    const riskReduction = this.calculateRiskReduction(event);
    const implementationCost = this.calculateImplementationCost(event);
    const duration = this.estimateDuration(event);

    // WSJF calculation
    const costOfDelay = businessImpact + timeCriticality + riskReduction;
    const wsjfScore = (costOfDelay * riskAdjustedCOD) / duration;

    // ROI calculations
    const roi = this.calculateROI(businessImpact, implementationCost, duration);
    const npv = this.calculateNPV(businessImpact, implementationCost, duration);

    // Economic trend analysis
    const economicTrend = this.analyzeEconomicTrend(event, baseCOD);

    // Circle impact analysis
    const circleImpact = this.calculateCircleEconomicImpact(event, businessImpact, implementationCost);

    // Category economics
    const categoryEconomics = this.getCategoryEconomics(event);

    // Business value correlation
    const businessCorrelation = this.calculateBusinessValueCorrelation(event);

    return {
      cod: baseCOD,
      wsjf_score: wsjfScore,
      risk_adjusted_cod: riskAdjustedCOD,
      time_criticality_factor: timeCriticality,
      business_impact: businessImpact,
      user_value: userValue,
      risk_reduction_value: riskReduction,
      implementation_cost: implementationCost,
      duration,
      roi,
      npv,
      economic_trend: economicTrend,
      circle_impact: circleImpact,
      category_economics: categoryEconomics,
      business_correlation: businessCorrelation
    };
  }

  /**
   * Calculate base Cost of Delay for a pattern
   */
  private calculateBaseCOD(event: PatternEvent): number {
    const pattern = event.pattern;
    const tags = event.tags || [];
    const circle = event.circle;
    const depth = event.depth || 0;

    // Base COD calculation
    let baseCOD = 10; // Default base COD

    // Pattern-specific COD adjustments
    const patternMultipliers: Record<string, number> = {
      'safe-degrade': 2.0,
      'guardrail-lock': 1.8,
      'iteration-budget': 1.5,
      'observability-first': 1.3,
      'autocommit-shadow': 1.2,
      'circle-risk-focus': 1.4,
      'failure-strategy': 1.7,
      'depth-ladder': 1.1,
      'ml-training-guardrail': 1.6,
      'hpc-batch-window': 1.4,
      'stat-robustness-sweep': 1.2,
      'device-coverage': 1.3,
      'forensic-verification': 1.0,
      'wsjf-enrichment': 0.8,
      'code-fix-proposal': 1.1,
      'iterative-rca': 1.3
    };

    baseCOD *= patternMultipliers[pattern] ?? 1.0;

    // Category-based adjustments
    if (tags.includes('ML')) baseCOD *= 1.3;
    if (tags.includes('HPC')) baseCOD *= 1.2;
    if (tags.includes('Stats')) baseCOD *= 0.9;
    if (tags.includes('Device/Web')) baseCOD *= 1.0;

    // Depth-based adjustments (deeper = higher COD)
    const depthMultiplier = 1 + (depth * 0.15);
    baseCOD *= depthMultiplier;

    // Circle-based adjustments
    const circleMultipliers: Record<string, number> = {
      'governance': 1.2,
      'analyst': 1.1,
      'assessor': 1.0,
      'innovator': 1.3,
      'intuitive': 0.9,
      'orchestrator': 1.1,
      'seeker': 0.8,
      'retro': 0.7
    };

    baseCOD *= circleMultipliers[circle] ?? 1.0;

    // Time-based decay/increase
    const now = new Date();
    const eventTime = new Date(event.ts);
    const hoursSinceEvent = (now.getTime() - eventTime.getTime()) / (1000 * 60 * 60);

    // Older unresolved issues have higher COD
    const timeMultiplier = Math.min(1 + (hoursSinceEvent / 168), 3.0); // Cap at 3x after 1 week
    baseCOD *= timeMultiplier;

    return Math.round(baseCOD * 100) / 100;
  }

  /**
   * Calculate risk-adjusted Cost of Delay
   */
  private calculateRiskAdjustedCOD(event: PatternEvent, baseCOD: number): number {
    const tags = event.tags || [];
    const mutation = event.mutation || false;
    const mode = event.mode;

    let riskMultiplier = 1.0;

    // Risk factors
    if (mutation) riskMultiplier *= 1.3;
    if (mode === 'enforcement') riskMultiplier *= 1.2;
    if (mode === 'mutate') riskMultiplier *= 1.4;

    // Category-based risk
    if (tags.includes('ML')) riskMultiplier *= 1.2;
    if (tags.includes('HPC')) riskMultiplier *= 1.1;

    // Framework/scheduler complexity risk
    if (event.framework && event.scheduler) riskMultiplier *= 1.1;

    return Math.round(baseCOD * riskMultiplier * 100) / 100;
  }

  /**
   * Calculate time criticality factor
   */
  private calculateTimeCriticality(event: PatternEvent): number {
    const pattern = event.pattern;
    const circle = event.circle;
    const gate = event.gate;

    let criticality = 20; // Base time criticality (1-20 scale)

    // Gate-based adjustments
    const gateCriticality: Record<string, number> = {
      'health': 0.9,
      'governance': 1.1,
      'wsjf': 1.2,
      'focus': 1.0,
      'prod-cycle-gate': 1.3,
      'governance-review': 1.1,
      'retro-analysis': 0.8,
      'observability': 0.9,
      'circle-output': 1.0,
      'system-risk': 1.4,
      'calibration': 1.0
    };

    criticality *= gateCriticality[gate ?? ''] ?? 1.0;

    // Pattern-specific criticality
    const highCriticalityPatterns = ['safe-degrade', 'guardrail-lock', 'failure-strategy'];
    if (highCriticalityPatterns.includes(pattern)) {
      criticality *= 1.3;
    }

    // Circle-based adjustments
    const circleCriticality: Record<string, number> = {
      'governance': 1.1,
      'orchestrator': 1.2,
      'analyst': 1.0,
      'retro': 0.8
    };

    criticality *= circleCriticality[circle] ?? 1.0;

    return Math.round(Math.min(criticality, 20) * 100) / 100;
  }

  /**
   * Calculate business impact score
   */
  private calculateBusinessImpact(event: PatternEvent): number {
    const pattern = event.pattern;
    const tags = event.tags || [];
    const depth = event.depth || 0;

    let impact = 30; // Base business impact (1-100 scale)

    // Pattern-specific impact
    const patternImpact: Record<string, number> = {
      'safe-degrade': 70,
      'guardrail-lock': 65,
      'iteration-budget': 45,
      'observability-first': 55,
      'autocommit-shadow': 40,
      'circle-risk-focus': 50,
      'failure-strategy': 75,
      'depth-ladder': 35,
      'ml-training-guardrail': 60,
      'hpc-batch-window': 55,
      'stat-robustness-sweep': 45,
      'device-coverage': 50,
      'forensic-verification': 30,
      'wsjf-enrichment': 40,
      'code-fix-proposal': 60,
      'iterative-rca': 50
    };

    impact = patternImpact[pattern] ?? impact;

    // Depth-based impact scaling
    const depthScaling = 1 + (depth * 0.1);
    impact *= depthScaling;

    // Category-based adjustments
    if (tags.includes('ML')) impact *= 1.2;
    if (tags.includes('HPC')) impact *= 1.1;
    if (tags.includes('Stats')) impact *= 1.0;
    if (tags.includes('Device/Web')) impact *= 1.1;

    // Observability and forensic patterns have deferred but higher impact
    if (tags.includes('Observability') || tags.includes('Forensic')) {
      impact *= 1.3;
    }

    return Math.round(Math.min(impact, 100) * 100) / 100;
  }

  /**
   * Calculate user value score
   */
  private calculateUserValue(event: PatternEvent): number {
    const pattern = event.pattern;
    const tags = event.tags || [];
    const circle = event.circle;

    let userValue = 25; // Base user value (1-100 scale)

    // User-centric patterns have higher value
    const userCentricPatterns = [
      'observability-first', 'device-coverage', 'forensic-verification',
      'safe-degrade', 'autocommit-shadow'
    ];

    if (userCentricPatterns.includes(pattern)) {
      userValue *= 1.5;
    }

    // Circle-based user value
    const circleUserValue: Record<string, number> = {
      'analyst': 1.2,
      'assessor': 1.1,
      'intuitive': 1.3,
      'seeker': 1.4
    };

    userValue *= circleUserValue[circle] ?? 1.0;

    // Category adjustments
    if (tags.includes('Device/Web')) userValue *= 1.3;
    if (tags.includes('ML')) userValue *= 1.1;
    if (tags.includes('Stats')) userValue *= 1.0;

    return Math.round(Math.min(userValue, 100) * 100) / 100;
  }

  /**
   * Calculate risk reduction value
   */
  private calculateRiskReduction(event: PatternEvent): number {
    const pattern = event.pattern;
    const tags = event.tags || [];
    const mode = event.mode;

    let riskReduction = 20; // Base risk reduction (1-100 scale)

    // High risk reduction patterns
    const highRiskReductionPatterns = [
      'safe-degrade', 'guardrail-lock', 'failure-strategy',
      'ml-training-guardrail', 'hpc-batch-window', 'stat-robustness-sweep'
    ];

    if (highRiskReductionPatterns.includes(pattern)) {
      riskReduction *= 1.8;
    }

    // Mode-based risk reduction
    if (mode === 'enforcement') riskReduction *= 1.3;
    if (mode === 'mutate') riskReduction *= 1.1;

    // Category-based risk profiles
    if (tags.includes('ML')) riskReduction *= 1.4; // High uncertainty
    if (tags.includes('HPC')) riskReduction *= 1.2; // Resource intensive
    if (tags.includes('Stats')) riskReduction *= 1.1; // Statistical validity

    return Math.round(Math.min(riskReduction, 100) * 100) / 100;
  }

  /**
   * Calculate implementation cost
   */
  private calculateImplementationCost(event: PatternEvent): number {
    const pattern = event.pattern;
    const tags = event.tags || [];
    const depth = event.depth || 0;

    let baseCost = 20; // Base implementation cost

    // Pattern complexity costs
    const patternCosts: Record<string, number> = {
      'safe-degrade': 15,
      'guardrail-lock': 20,
      'iteration-budget': 10,
      'observability-first': 25,
      'autocommit-shadow': 30,
      'circle-risk-focus': 15,
      'failure-strategy': 35,
      'depth-ladder': 8,
      'ml-training-guardrail': 50,
      'hpc-batch-window': 40,
      'stat-robustness-sweep': 30,
      'device-coverage': 35,
      'forensic-verification': 25,
      'wsjf-enrichment': 20,
      'code-fix-proposal': 45,
      'iterative-rca': 30
    };

    baseCost = patternCosts[pattern] ?? baseCost;

    // Category-based cost adjustments
    if (tags.includes('ML')) baseCost *= 1.5;
    if (tags.includes('HPC')) baseCost *= 1.3;
    if (tags.includes('Stats')) baseCost *= 1.1;
    if (tags.includes('Device/Web')) baseCost *= 1.2;

    // Depth-based cost scaling
    const depthCostScaling = 1 + (depth * 0.08);
    baseCost *= depthCostScaling;

    // Framework and scheduler complexity
    if (event.framework && event.framework.length > 0) baseCost *= 1.1;
    if (event.scheduler && event.scheduler.length > 0) baseCost *= 1.1;

    return Math.round(baseCost * 100) / 100;
  }

  /**
   * Estimate implementation duration in hours
   */
  private estimateDuration(event: PatternEvent): number {
    const pattern = event.pattern;
    const tags = event.tags || [];
    const implementationCost = this.calculateImplementationCost(event);

    // Base duration calculation (hours)
    let baseDuration = implementationCost / 10; // Rough conversion from cost to hours

    // Pattern-specific duration adjustments
    const durationMultipliers: Record<string, number> = {
      'ml-training-guardrail': 2.0,  // Training takes time
      'hpc-batch-window': 1.8,       // HPC operations are complex
      'stat-robustness-sweep': 1.5,  // Statistical analysis
      'device-coverage': 1.3,        // Device testing
      'forensic-verification': 1.4,  // Analysis intensive
      'code-fix-proposal': 1.2,      // Code development
      'observability-first': 1.1     // Setup time
    };

    baseDuration *= durationMultipliers[pattern] ?? 1.0;

    // Category-based adjustments
    if (tags.includes('ML')) baseDuration *= 1.4; // ML model training time
    if (tags.includes('HPC')) baseDuration *= 1.2; // Resource scheduling time

    // Minimum duration of 1 hour
    return Math.max(Math.round(baseDuration), 1);
  }

  /**
   * Calculate Return on Investment
   */
  private calculateROI(businessImpact: number, implementationCost: number, duration: number): number {
    if (implementationCost <= 0) return 0;

    // Simple ROI calculation with time decay
    const timeDecayFactor = Math.exp(-duration / 168); // Decay over weeks
    const adjustedImpact = businessImpact * timeDecayFactor;

    return Math.round(((adjustedImpact - implementationCost) / implementationCost) * 100 * 100) / 100;
  }

  /**
   * Calculate Net Present Value
   */
  private calculateNPV(businessImpact: number, implementationCost: number, duration: number): number {
    const discountRate = this.parameters.discount_rate / 365; // Daily rate
    const timeHorizon = Math.min(duration, this.parameters.time_horizon);

    let npv = -implementationCost; // Initial investment

    // Discounted cash flows (simplified model)
    const dailyBenefit = businessImpact / Math.max(duration, 1);
    for (let day = 1; day <= timeHorizon; day++) {
      npv += dailyBenefit / Math.pow(1 + discountRate, day);
    }

    return Math.round(npv * 100) / 100;
  }

  /**
   * Analyze economic trend
   */
  private analyzeEconomicTrend(event: PatternEvent, currentCOD: number): EconomicTrend {
    const pattern = event.pattern;
    const recentEvents = this.historicalData
      .filter(e => e.pattern === pattern)
      .sort((a, b) => new Date(b.ts).getTime() - new Date(a.ts).getTime())
      .slice(0, 10);

    let trend: 'increasing' | 'decreasing' | 'stable' = 'stable';
    let trendPercentage = 0;
    let forecastedCOD = currentCOD;

    if (recentEvents.length >= 3) {
      const recentCODs = recentEvents.map(e =>
        (e as any).economic?.cod || this.calculateBaseCOD(e)
      );

      // Simple linear trend analysis
      const avgCOD = recentCODs.reduce((a, b) => a + b, 0) / recentCODs.length;
      const oldestCOD = recentCODs[recentCODs.length - 1];
      const newestCOD = recentCODs[0];

      if (newestCOD > oldestCOD * 1.1) {
        trend = 'increasing';
        trendPercentage = ((newestCOD - oldestCOD) / oldestCOD) * 100;
      } else if (newestCOD < oldestCOD * 0.9) {
        trend = 'decreasing';
        trendPercentage = ((oldestCOD - newestCOD) / oldestCOD) * 100;
      }

      // Simple forecast
      if (trend === 'increasing') {
        forecastedCOD = currentCOD * 1.1;
      } else if (trend === 'decreasing') {
        forecastedCOD = currentCOD * 0.9;
      }
    }

    // Calculate confidence interval
    const confidenceInterval: [number, number] = [
      forecastedCOD * 0.8,
      forecastedCOD * 1.2
    ];

    // Economic velocity (COD per day)
    const now = new Date();
    const oldestEvent = recentEvents[recentEvents.length - 1];
    const daysSpan = oldestEvent ?
      (now.getTime() - new Date(oldestEvent.ts).getTime()) / (1000 * 60 * 60 * 24) : 1;

    const economicVelocity = currentCOD / Math.max(daysSpan, 1);

    return {
      cod_trend: trend,
      trend_percentage: Math.round(trendPercentage * 100) / 100,
      forecasted_cod: Math.round(forecastedCOD * 100) / 100,
      confidence_interval: confidenceInterval.map(v => Math.round(v * 100) / 100) as [number, number],
      economic_velocity: Math.round(economicVelocity * 100) / 100
    };
  }

  /**
   * Calculate circle economic impact
   */
  private calculateCircleEconomicImpact(
    event: PatternEvent,
    businessImpact: number,
    implementationCost: number
  ): CircleEconomicImpact {
    const circle = event.circle ?? 'General';
    const profile = this.CIRCLE_ECONOMIC_PROFILES[circle] ?? {};

    const economicContribution = profile.economic_contribution || 1.0;
    const riskExposure = profile.risk_exposure || 0.5;

    const valueGenerated = businessImpact * economicContribution;
    const costIncurred = implementationCost * economicContribution;
    const efficiencyRatio = valueGenerated / Math.max(costIncurred, 1);

    return {
      circle: circle,
      economic_contribution: economicContribution,
      risk_exposure: riskExposure,
      value_generated: Math.round(valueGenerated * 100) / 100,
      cost_incurred: Math.round(costIncurred * 100) / 100,
      efficiency_ratio: Math.round(efficiencyRatio * 100) / 100
    };
  }

  /**
   * Get category economics data
   */
  private getCategoryEconomics(event: PatternEvent): CategoryEconomics {
    const tags = event.tags || [];

    for (const tag of tags) {
      if (this.CATEGORY_ECONOMICS[tag]) {
        return this.CATEGORY_ECONOMICS[tag];
      }
    }

    return this.CATEGORY_ECONOMICS['General']!;
  }

  /**
   * Calculate business value correlation
   */
  private calculateBusinessValueCorrelation(event: PatternEvent): BusinessValueCorrelation {
    const pattern = event.pattern ?? '';
    const tags = event.tags || [];
    const circle = event.circle ?? '';

    // Business objectives mapping
    const objectivesByPattern: Record<string, string[]> = {
      'safe-degrade': ['system-reliability', 'user-satisfaction', 'business-continuity'],
      'guardrail-lock': ['risk-mitigation', 'compliance', 'quality-assurance'],
      'observability-first': ['operational-excellence', 'performance-monitoring', 'issue-detection'],
      'ml-training-guardrail': ['model-quality', 'reliability', 'cost-optimization'],
      'hpc-batch-window': ['resource-optimization', 'throughput-improvement', 'cost-efficiency'],
      'device-coverage': ['user-experience', 'compatibility', 'market-reach'],
      'forensic-verification': ['quality-assurance', 'root-cause-analysis', 'continuous-improvement'],
      'autocommit-shadow': ['developer-productivity', 'automation', 'speed-to-market'],
      'circle-risk-focus': ['resource-allocation', 'risk-management', 'team-optimization'],
      'failure-strategy': ['resilience', 'recovery-time', 'business-continuity']
    };

    const objectives_affected = objectivesByPattern[pattern] ?? ['general-improvement'];

    // KPI impact scores (simplified model)
    const kpi_impact: Record<string, number> = {
      'reliability': this.calculateKPIImpact(pattern, 'reliability', tags),
      'performance': this.calculateKPIImpact(pattern, 'performance', tags),
      'cost': this.calculateKPIImpact(pattern, 'cost', tags),
      'quality': this.calculateKPIImpact(pattern, 'quality', tags),
      'user-satisfaction': this.calculateKPIImpact(pattern, 'user-satisfaction', tags),
      'time-to-market': this.calculateKPIImpact(pattern, 'time-to-market', tags)
    };

    // Stakeholder value mapping
    const stakeholder_value: Record<string, number> = {
      'customers': this.calculateStakeholderValue(pattern, 'customers', circle),
      'developers': this.calculateStakeholderValue(pattern, 'developers', circle),
      'operations': this.calculateStakeholderValue(pattern, 'operations', circle),
      'management': this.calculateStakeholderValue(pattern, 'management', circle),
      'compliance': this.calculateStakeholderValue(pattern, 'compliance', circle)
    };

    // Market impact assessment
    const market_impact = this.calculateMarketImpact(pattern, tags);

    // Customer value score
    const customer_value = this.calculateCustomerValue(pattern, circle, tags);

    // Competitive advantage score
    const competitive_advantage = this.calculateCompetitiveAdvantage(pattern, tags);

    return {
      objectives_affected,
      kpi_impact,
      stakeholder_value,
      market_impact,
      customer_value,
      competitive_advantage
    };
  }

  private calculateKPIImpact(pattern: string, kpi: string, tags: string[]): number {
    const impacts: Record<string, Record<string, number>> = {
      'safe-degrade': {
        'reliability': 80, 'performance': 60, 'cost': 40, 'quality': 70,
        'user-satisfaction': 75, 'time-to-market': 30
      },
      'observability-first': {
        'reliability': 60, 'performance': 70, 'cost': 50, 'quality': 80,
        'user-satisfaction': 65, 'time-to-market': 40
      },
      'ml-training-guardrail': {
        'reliability': 85, 'performance': 65, 'cost': 75, 'quality': 90,
        'user-satisfaction': 70, 'time-to-market': 35
      },
      'autocommit-shadow': {
        'reliability': 50, 'performance': 40, 'cost': 60, 'quality': 60,
        'user-satisfaction': 55, 'time-to-market': 85
      }
    };

    const baseImpact = impacts[pattern]?.[kpi] || 30;

    // Tag-based adjustments
    let adjustment = 1.0;
    if (tags.includes('ML') && kpi === 'quality') adjustment *= 1.2;
    if (tags.includes('HPC') && kpi === 'performance') adjustment *= 1.3;
    if (tags.includes('Device/Web') && kpi === 'user-satisfaction') adjustment *= 1.4;

    return Math.round(Math.min(baseImpact * adjustment, 100));
  }

  private calculateStakeholderValue(pattern: string, stakeholder: string, circle: string): number {
    const values: Record<string, Record<string, number>> = {
      'customers': {
        'safe-degrade': 80, 'observability-first': 70, 'device-coverage': 90,
        'guardrail-lock': 60, 'autocommit-shadow': 50
      },
      'developers': {
        'autocommit-shadow': 90, 'observability-first': 75, 'safe-degrade': 65,
        'forensic-verification': 80, 'code-fix-proposal': 85
      },
      'operations': {
        'safe-degrade': 85, 'hpc-batch-window': 80, 'observability-first': 75,
        'guardrail-lock': 70, 'failure-strategy': 90
      },
      'management': {
        'circle-risk-focus': 80, 'wsjf-enrichment': 85, 'governance-agent': 75,
        'iteration-budget': 70, 'autocommit-shadow': 60
      }
    };

    const baseValue = values[stakeholder]?.[pattern] || 40;

    // Circle-based adjustments
    const circleAdjustments: Record<string, Record<string, number>> = {
      'governance': { 'management': 1.3, 'compliance': 1.4 },
      'analyst': { 'management': 1.1, 'customers': 1.0 },
      'retro': { 'developers': 1.2, 'operations': 1.1 }
    };

    const adjustment = circleAdjustments[circle]?.[stakeholder] || 1.0;

    return Math.round(Math.min(baseValue * adjustment, 100));
  }

  private calculateMarketImpact(pattern: string, tags: string[]): number {
    let impact = 30; // Base market impact

    // High market impact patterns
    const highImpactPatterns = [
      'device-coverage', 'ml-training-guardrail', 'hpc-batch-window',
      'autocommit-shadow', 'observability-first'
    ];

    if (highImpactPatterns.includes(pattern)) {
      impact *= 1.5;
    }

    // Tag-based market impact
    if (tags.includes('Device/Web')) impact *= 1.4; // Direct customer impact
    if (tags.includes('ML')) impact *= 1.3; // AI/ML market advantage
    if (tags.includes('HPC')) impact *= 1.1; // Performance advantage

    return Math.round(Math.min(impact, 100));
  }

  private calculateCustomerValue(pattern: string, circle: string, tags: string[]): number {
    let value = 40; // Base customer value

    // Customer-centric patterns
    const customerCentricPatterns = [
      'safe-degrade', 'device-coverage', 'observability-first',
      'forensic-verification', 'failure-strategy'
    ];

    if (customerCentricPatterns.includes(pattern)) {
      value *= 1.4;
    }

    // Tag-based customer value
    if (tags.includes('Device/Web')) value *= 1.5;
    if (tags.includes('Observability')) value *= 1.2;

    // Circle-based customer focus
    const customerFocusedCircles = ['analyst', 'assessor', 'intuitive', 'seeker'];
    if (customerFocusedCircles.includes(circle)) {
      value *= 1.1;
    }

    return Math.round(Math.min(value, 100));
  }

  private calculateCompetitiveAdvantage(pattern: string, tags: string[]): number {
    let advantage = 25; // Base competitive advantage

    // Innovation-driven patterns
    const innovationPatterns = [
      'ml-training-guardrail', 'autocommit-shadow', 'wsjf-enrichment',
      'code-fix-proposal', 'iterative-rca'
    ];

    if (innovationPatterns.includes(pattern)) {
      advantage *= 1.6;
    }

    // Technology advantage tags
    if (tags.includes('ML')) advantage *= 1.4; // AI advantage
    if (tags.includes('HPC')) advantage *= 1.2; // Performance advantage
    if (tags.includes('Stats')) advantage *= 1.1; // Data advantage

    return Math.round(Math.min(advantage, 100));
  }

  /**
   * Calculate comprehensive ROI metrics over time
   */
  public calculateROIMetrics(event: PatternEvent, timeHorizon: number = 30): ROIMetrics {
    const businessImpact = this.calculateBusinessImpact(event);
    const implementationCost = this.calculateImplementationCost(event);
    const duration = this.estimateDuration(event);

    const initial_investment = implementationCost;
    const returns: number[] = [];
    const time_periods: string[] = [];

    let cumulativeReturn = 0;
    let cumulativeROI = -initial_investment;
    let paybackPeriod = 0;
    let paybackFound = false;

    // Calculate returns over time horizon
    for (let period = 1; period <= timeHorizon; period++) {
      // Time-decay factor for returns
      const decayFactor = Math.exp(-period / (timeHorizon * 0.5));
      const periodReturn = (businessImpact / timeHorizon) * decayFactor;

      returns.push(periodReturn);
      cumulativeReturn += periodReturn;
      cumulativeROI += periodReturn;

      time_periods.push(`Day ${period}`);

      // Find payback period
      if (!paybackFound && cumulativeROI >= 0) {
        paybackPeriod = period;
        paybackFound = true;
      }
    }

    const roi_rate = ((cumulativeReturn - initial_investment) / initial_investment) * 100;

    // Risk-adjusted ROI
    const riskMultiplier = 0.8; // Assuming 20% risk adjustment
    const risk_adjusted_roi = roi_rate * riskMultiplier;

    return {
      initial_investment,
      returns: returns.map(r => Math.round(r * 100) / 100),
      time_periods,
      cumulative_roi: Math.round(cumulativeROI * 100) / 100,
      payback_period: paybackPeriod || timeHorizon,
      roi_rate: Math.round(roi_rate * 100) / 100,
      risk_adjusted_roi: Math.round(risk_adjusted_roi * 100) / 100
    };
  }

  /**
   * Generate economic impact report for multiple events
   */
  public generateEconomicReport(events: PatternEvent[]): {
    summary: EconomicSummary;
    events: Array<{ event: PatternEvent; metrics: EnhancedEconomicData }>;
    trends: EconomicTrends;
    recommendations: EconomicRecommendation[];
  } {
    const eventMetrics = events.map(event => ({
      event,
      metrics: this.calculateEconomicMetrics(event)
    }));

    const summary = this.calculateEconomicSummary(eventMetrics);
    const trends = this.analyzeEconomicTrends(eventMetrics);
    const recommendations = this.generateEconomicRecommendations(summary, trends);

    return {
      summary,
      events: eventMetrics,
      trends,
      recommendations
    };
  }

  private calculateEconomicSummary(
    eventMetrics: Array<{ event: PatternEvent; metrics: EnhancedEconomicData }>
  ): EconomicSummary {
    const totalCOD = eventMetrics.reduce((sum, em) => sum + em.metrics.cod, 0);
    const avgWSJF = eventMetrics.reduce((sum, em) => sum + em.metrics.wsjf_score, 0) / eventMetrics.length;
    const totalBusinessImpact = eventMetrics.reduce((sum, em) => sum + em.metrics.business_impact, 0);
    const totalImplementationCost = eventMetrics.reduce((sum, em) => sum + em.metrics.implementation_cost, 0);
    const avgROI = eventMetrics.reduce((sum, em) => sum + em.metrics.roi, 0) / eventMetrics.length;
    const totalNPV = eventMetrics.reduce((sum, em) => sum + em.metrics.npv, 0);

    // Circle breakdown
    const circleBreakdown: Record<string, CircleEconomicSummary> = {};
    eventMetrics.forEach(({ event, metrics }) => {
      const circle = event.circle;
      if (!circleBreakdown[circle]) {
        circleBreakdown[circle] = {
          circle,
          total_cod: 0,
          avg_wsjf: 0,
          total_business_impact: 0,
          total_implementation_cost: 0,
          avg_roi: 0,
          event_count: 0,
          efficiency_ratio: 0
        };
      }

      const summary = circleBreakdown[circle];
      summary.total_cod += metrics.cod;
      summary.total_business_impact += metrics.business_impact;
      summary.total_implementation_cost += metrics.implementation_cost;
      summary.event_count++;
    });

    // Calculate averages and efficiency
    Object.values(circleBreakdown).forEach(summary => {
      summary.avg_wsjf = eventMetrics
        .filter(em => em.event.circle === summary.circle)
        .reduce((sum, em) => sum + em.metrics.wsjf_score, 0) / summary.event_count;
      summary.avg_roi = eventMetrics
        .filter(em => em.event.circle === summary.circle)
        .reduce((sum, em) => sum + em.metrics.roi, 0) / summary.event_count;
      summary.efficiency_ratio = summary.total_business_impact / Math.max(summary.total_implementation_cost, 1);
    });

    return {
      total_events: eventMetrics.length,
      total_cod: Math.round(totalCOD * 100) / 100,
      avg_wsjf: Math.round(avgWSJF * 100) / 100,
      total_business_impact: Math.round(totalBusinessImpact * 100) / 100,
      total_implementation_cost: Math.round(totalImplementationCost * 100) / 100,
      overall_roi: Math.round(avgROI * 100) / 100,
      total_npv: Math.round(totalNPV * 100) / 100,
      circle_breakdown: circleBreakdown
    };
  }

  private analyzeEconomicTrends(
    eventMetrics: Array<{ event: PatternEvent; metrics: EnhancedEconomicData }>
  ): EconomicTrends {
    // Time-based analysis
    const sortedByTime = eventMetrics.sort((a, b) =>
      new Date(a.event.ts).getTime() - new Date(b.event.ts).getTime()
    );

    const codTrend = this.calculateTrend(sortedByTime.map(em => em.metrics.cod));
    const wsjfTrend = this.calculateTrend(sortedByTime.map(em => em.metrics.wsjf_score));
    const roiTrend = this.calculateTrend(sortedByTime.map(em => em.metrics.roi));

    // Pattern category trends
    const categoryTrends: Record<string, any> = {};
    eventMetrics.forEach(({ event, metrics }) => {
      const tags = event.tags || [];
      const category = tags.find(tag => this.CATEGORY_ECONOMICS[tag]) || 'General';

      if (!categoryTrends[category]) {
        categoryTrends[category] = { cod: [], wsjf: [], roi: [] };
      }

      categoryTrends[category].cod.push(metrics.cod);
      categoryTrends[category].wsjf.push(metrics.wsjf_score);
      categoryTrends[category].roi.push(metrics.roi);
    });

    // Calculate category trend directions
    Object.keys(categoryTrends).forEach(category => {
      const data = categoryTrends[category];
      categoryTrends[category] = {
        cod_trend: this.calculateTrendDirection(data.cod),
        wsjf_trend: this.calculateTrendDirection(data.wsjf),
        roi_trend: this.calculateTrendDirection(data.roi),
        avg_cod: data.cod.reduce((a: number, b: number) => a + b, 0) / data.cod.length,
        avg_wsjf: data.wsjf.reduce((a: number, b: number) => a + b, 0) / data.wsjf.length,
        avg_roi: data.roi.reduce((a: number, b: number) => a + b, 0) / data.roi.length
      };
    });

    return {
      overall_trends: {
        cod_trend: this.calculateTrendDirection(codTrend),
        wsjf_trend: this.calculateTrendDirection(wsjfTrend),
        roi_trend: this.calculateTrendDirection(roiTrend)
      },
      category_trends: categoryTrends,
      economic_velocity: this.calculateEconomicVelocity(sortedByTime)
    };
  }

  private calculateTrend(values: number[]): 'increasing' | 'decreasing' | 'stable' {
    if (values.length < 2) return 'stable';

    const firstHalf = values.slice(0, Math.floor(values.length / 2));
    const secondHalf = values.slice(Math.floor(values.length / 2));

    const firstAvg = firstHalf.reduce((a, b) => a + b, 0) / firstHalf.length;
    const secondAvg = secondHalf.reduce((a, b) => a + b, 0) / secondHalf.length;

    const change = (secondAvg - firstAvg) / firstAvg;

    if (change > 0.1) return 'increasing';
    if (change < -0.1) return 'decreasing';
    return 'stable';
  }

  private calculateTrendDirection(values: number[]): 'increasing' | 'decreasing' | 'stable' {
    return this.calculateTrend(values);
  }

  private calculateEconomicVelocity(
    sortedEvents: Array<{ event: PatternEvent; metrics: EnhancedEconomicData }>
  ): number {
    if (sortedEvents.length < 2) return 0;

    const firstEvent = sortedEvents[0];
    const lastEvent = sortedEvents[sortedEvents.length - 1];

    const daysDiff = (new Date(lastEvent.event.ts).getTime() - new Date(firstEvent.event.ts).getTime()) / (1000 * 60 * 60 * 24);

    if (daysDiff <= 0) return 0;

    const totalEconomicValue = sortedEvents.reduce((sum, em) => sum + em.metrics.business_impact, 0);

    return Math.round((totalEconomicValue / daysDiff) * 100) / 100;
  }

  private generateEconomicRecommendations(
    summary: EconomicSummary,
    trends: EconomicTrends
  ): EconomicRecommendation[] {
    const recommendations: EconomicRecommendation[] = [];

    // High COD items
    if (summary.total_cod > 100) {
      recommendations.push({
        type: 'cost-optimization',
        priority: 'high',
        title: 'Reduce Cost of Delay',
        description: `Total COD of ${summary.total_cod} is above threshold. Focus on high-WSJF items to reduce economic impact.`,
        action_items: [
          'Prioritize items with WSJF score > 10',
          'Implement parallel execution where possible',
          'Consider resource reallocation to critical items'
        ],
        expected_impact: '20-30% COD reduction',
        implementation_cost: 'Medium',
        timeframe: '2-4 weeks'
      });
    }

    // Low ROI items
    if (summary.overall_roi < 50) {
      recommendations.push({
        type: 'roi-improvement',
        priority: 'medium',
        title: 'Improve Return on Investment',
        description: `Overall ROI of ${summary.overall_roi}% is below target. Focus on patterns with higher business value or lower implementation cost.`,
        action_items: [
          'Re-evaluate low-ROI pattern implementations',
          'Look for automation opportunities to reduce costs',
          'Focus on patterns with higher business impact'
        ],
        expected_impact: '15-25% ROI improvement',
        implementation_cost: 'Low',
        timeframe: '1-2 weeks'
      });
    }

    // Trend-based recommendations
    if (trends.overall_trends.cod_trend === 'increasing') {
      recommendations.push({
        type: 'trend-reversal',
        priority: 'high',
        title: 'Address Increasing Cost of Delay',
        description: 'COD trend is increasing over time. Immediate action needed to reverse this trend.',
        action_items: [
          'Identify root causes of increasing COD',
          'Implement preventative measures',
          'Increase monitoring and early intervention'
        ],
        expected_impact: 'Stabilize or reduce COD trend',
        implementation_cost: 'Medium',
        timeframe: '1-3 weeks'
      });
    }

    // Circle-specific recommendations
    Object.values(summary.circle_breakdown).forEach(circle => {
      if (circle.efficiency_ratio < 1.0) {
        recommendations.push({
          type: 'circle-optimization',
          priority: 'medium',
          title: `Optimize ${circle.circle} Circle Economic Efficiency`,
          description: `${circle.circle} circle efficiency ratio of ${circle.efficiency_ratio} indicates costs exceed benefits.`,
          action_items: [
            'Review pattern effectiveness in this circle',
            'Consider process improvements or automation',
            'Reallocate resources to higher-impact activities'
          ],
          expected_impact: `Improve efficiency ratio to >1.2 for ${circle.circle}`,
          implementation_cost: 'Low-Medium',
          timeframe: '2-3 weeks'
        });
      }
    });

    return recommendations;
  }
}

// Supporting interfaces
export interface EconomicSummary {
  total_events: number;
  total_cod: number;
  avg_wsjf: number;
  total_business_impact: number;
  total_implementation_cost: number;
  overall_roi: number;
  total_npv: number;
  circle_breakdown: Record<string, CircleEconomicSummary>;
}

export interface CircleEconomicSummary {
  circle: string;
  total_cod: number;
  avg_wsjf: number;
  total_business_impact: number;
  total_implementation_cost: number;
  avg_roi: number;
  event_count: number;
  efficiency_ratio: number;
}

export interface EconomicTrends {
  overall_trends: {
    cod_trend: 'increasing' | 'decreasing' | 'stable';
    wsjf_trend: 'increasing' | 'decreasing' | 'stable';
    roi_trend: 'increasing' | 'decreasing' | 'stable';
  };
  category_trends: Record<string, any>;
  economic_velocity: number;
}

export interface EconomicRecommendation {
  type: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  description: string;
  action_items: string[];
  expected_impact: string;
  implementation_cost: 'Low' | 'Medium' | 'High';
  timeframe: string;
}
