#!/usr/bin/env bash
set -euo pipefail

#═══════════════════════════════════════════════════════════════════════════
# CONSOLIDATION TRUTH REPORT GENERATOR
#
# Analyzes validation results and generates comprehensive truth report
# Input: JSON from validation-runner.js
# Output: CONSOLIDATION-TRUTH-REPORT.md
#═══════════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RESULTS_FILE="${1:-/tmp/validation-results.json}"
REPORT_FILE="${2:-$PROJECT_ROOT/docs/CONSOLIDATION-TRUTH-REPORT.md}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  CONSOLIDATION TRUTH REPORT GENERATOR${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Check if results file exists
if [[ ! -f "$RESULTS_FILE" ]]; then
  echo -e "${RED}❌ Results file not found: $RESULTS_FILE${NC}"
  exit 1
fi

# Parse JSON results
TIMESTAMP=$(jq -r '.timestamp' "$RESULTS_FILE")
NODE_VERSION=$(jq -r '.environment.node_version' "$RESULTS_FILE")
PLATFORM=$(jq -r '.environment.platform' "$RESULTS_FILE")
TOTAL_TESTS=$(jq -r '.summary.total_tests' "$RESULTS_FILE")
PASSED=$(jq -r '.summary.passed' "$RESULTS_FILE")
FAILED=$(jq -r '.summary.failed' "$RESULTS_FILE")

echo -e "${GREEN}📊 Analysis Parameters:${NC}"
echo "  Timestamp: $TIMESTAMP"
echo "  Node: $NODE_VERSION"
echo "  Platform: $PLATFORM"
echo "  Total Tests: $TOTAL_TESTS"
echo "  Passed: $PASSED"
echo "  Failed: $FAILED"
echo ""

# Generate report
cat > "$REPORT_FILE" << 'REPORT_HEADER'
# CONSOLIDATION TRUTH REPORT

**This is not aspirational documentation. This is proven truth.**

Generated by automated validation pipeline.
All claims in this document are backed by passing tests.

---

REPORT_HEADER

# Add metadata
cat >> "$REPORT_FILE" << REPORT_META

## 📋 Report Metadata

- **Generated**: $TIMESTAMP
- **Environment**: Node $NODE_VERSION on $PLATFORM
- **Total Tests Executed**: $TOTAL_TESTS
- **Tests Passed**: $PASSED ($(awk "BEGIN {printf \"%.1f\", ($PASSED/$TOTAL_TESTS)*100}")%)
- **Tests Failed**: $FAILED

---

REPORT_META

# Executive Summary
cat >> "$REPORT_FILE" << 'REPORT_EXEC_START'

## 🎯 Executive Summary: What Works NOW

REPORT_EXEC_START

# Extract proven working validators
WORKING_COUNT=$(jq -r '.summary.proven_working | length' "$RESULTS_FILE")
if [[ $WORKING_COUNT -gt 0 ]]; then
  cat >> "$REPORT_FILE" << REPORT_WORKING

### ✅ PROVEN WORKING Validators

$(jq -r '.summary.proven_working[] | "- **\(.)**"' "$RESULTS_FILE")

**These validators have passing tests and can be relied upon.**

REPORT_WORKING
else
  cat >> "$REPORT_FILE" << 'REPORT_NO_WORKING'

### ⚠️ NO FULLY WORKING VALIDATORS

All tested validators have failures or are partially implemented.

REPORT_NO_WORKING
fi

# Extract broken capabilities
cat >> "$REPORT_FILE" << 'REPORT_BROKEN_START'

### ❌ PROVEN BROKEN Capabilities

REPORT_BROKEN_START

jq -r '.summary.proven_broken[]' "$RESULTS_FILE" | sort -u | while read -r broken; do
  echo "- $broken" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << 'REPORT_BROKEN_END'

**These capabilities fail tests and should not be used in production.**

---

REPORT_BROKEN_END

# Detailed validator breakdown
cat >> "$REPORT_FILE" << 'REPORT_DETAILED_START'

## 🔬 Detailed Validator Analysis

REPORT_DETAILED_START

# For each validator
jq -c '.validators[]' "$RESULTS_FILE" | while read -r validator; do
  NAME=$(echo "$validator" | jq -r '.name')
  COMPONENT=$(echo "$validator" | jq -r '.component')
  STATUS=$(echo "$validator" | jq -r '.overall_status')

  # Status emoji
  case "$STATUS" in
    FULLY_WORKING)
      STATUS_EMOJI="✅"
      STATUS_COLOR="🟢"
      ;;
    PARTIALLY_WORKING)
      STATUS_EMOJI="⚠️"
      STATUS_COLOR="🟡"
      ;;
    BROKEN)
      STATUS_EMOJI="❌"
      STATUS_COLOR="🔴"
      ;;
    *)
      STATUS_EMOJI="❓"
      STATUS_COLOR="⚪"
      ;;
  esac

  cat >> "$REPORT_FILE" << VALIDATOR_HEADER

### $STATUS_EMOJI $NAME

- **Component**: \`$COMPONENT\`
- **Status**: $STATUS_COLOR $STATUS

VALIDATOR_HEADER

  # Proven capabilities
  PROVEN_COUNT=$(echo "$validator" | jq -r '.proven_capabilities | length')
  if [[ $PROVEN_COUNT -gt 0 ]]; then
    echo "" >> "$REPORT_FILE"
    echo "**✅ Proven Working:**" >> "$REPORT_FILE"
    echo "$validator" | jq -r '.proven_capabilities[] | "- \(.)"' >> "$REPORT_FILE"
  fi

  # Broken capabilities
  BROKEN_COUNT=$(echo "$validator" | jq -r '.broken_capabilities | length')
  if [[ $BROKEN_COUNT -gt 0 ]]; then
    echo "" >> "$REPORT_FILE"
    echo "**❌ Broken:**" >> "$REPORT_FILE"
    echo "$validator" | jq -r '.broken_capabilities[] | "- \(.)"' >> "$REPORT_FILE"
  fi

  # Anti-patterns
  ANTI_COUNT=$(echo "$validator" | jq -r '.anti_patterns | length')
  if [[ $ANTI_COUNT -gt 0 ]]; then
    echo "" >> "$REPORT_FILE"
    echo "**🚨 Anti-Patterns Detected:**" >> "$REPORT_FILE"
    echo "$validator" | jq -r '.anti_patterns[] | "- \(.)"' >> "$REPORT_FILE"
  fi

  # Test results table
  echo "" >> "$REPORT_FILE"
  echo "**Test Results:**" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "| Test | Status | Time | Message |" >> "$REPORT_FILE"
  echo "|------|--------|------|---------|" >> "$REPORT_FILE"

  echo "$validator" | jq -c '.tests[]' | while read -r test; do
    TEST_NAME=$(echo "$test" | jq -r '.name')
    TEST_STATUS=$(echo "$test" | jq -r '.status')
    TEST_TIME=$(echo "$test" | jq -r '.time_ms')
    TEST_MSG=$(echo "$test" | jq -r '.message' | head -c 80)

    case "$TEST_STATUS" in
      PASS) TEST_EMOJI="✅" ;;
      FAIL) TEST_EMOJI="❌" ;;
      EXPECTED_FAIL) TEST_EMOJI="⚠️" ;;
      *) TEST_EMOJI="❓" ;;
    esac

    echo "| $TEST_NAME | $TEST_EMOJI $TEST_STATUS | ${TEST_TIME}ms | $TEST_MSG |" >> "$REPORT_FILE"
  done

  echo "" >> "$REPORT_FILE"
  echo "---" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
done

# Recommendations section
cat >> "$REPORT_FILE" << 'REPORT_RECOMMENDATIONS'

## 🔧 Recommended Actions

Based on test results, here are concrete next steps:

### Immediate Fixes Required

REPORT_RECOMMENDATIONS

# Extract common failure patterns
cat >> "$REPORT_FILE" << 'REPORT_PATTERNS'

### Common Failure Patterns Observed

REPORT_PATTERNS

jq -r '.validators[].anti_patterns[]' "$RESULTS_FILE" | sort -u | while read -r pattern; do
  echo "- $pattern" >> "$REPORT_FILE"
done

# Baseline metrics
cat >> "$REPORT_FILE" << REPORT_BASELINE

---

## 📈 Baseline Metrics (Current State)

- **Total Validators Tested**: $(jq -r '.validators | length' "$RESULTS_FILE")
- **Fully Working**: $(jq -r '[.validators[] | select(.overall_status == "FULLY_WORKING")] | length' "$RESULTS_FILE")
- **Partially Working**: $(jq -r '[.validators[] | select(.overall_status == "PARTIALLY_WORKING")] | length' "$RESULTS_FILE")
- **Broken**: $(jq -r '[.validators[] | select(.overall_status == "BROKEN")] | length' "$RESULTS_FILE")
- **Test Pass Rate**: $(awk "BEGIN {printf \"%.1f%%\", ($PASSED/$TOTAL_TESTS)*100}")

### Performance Metrics

REPORT_BASELINE

# Calculate average test time
AVG_TIME=$(jq '[.validators[].tests[].time_ms] | add / length' "$RESULTS_FILE")
MAX_TIME=$(jq '[.validators[].tests[].time_ms] | max' "$RESULTS_FILE")

cat >> "$REPORT_FILE" << PERF_METRICS

- **Average Test Time**: ${AVG_TIME}ms
- **Slowest Test**: ${MAX_TIME}ms

PERF_METRICS

# Footer
cat >> "$REPORT_FILE" << 'REPORT_FOOTER'

---

## 🎯 Next Steps

1. **Fix Broken Validators**: Address all failing tests before claiming functionality
2. **Implement Stub Methods**: Replace TODO comments with actual implementations
3. **Add Missing Tests**: Ensure all public methods have test coverage
4. **Document Anti-Patterns**: Update documentation to reflect discovered issues
5. **Establish CI Gates**: Block merges if validators regress

---

**This report represents GROUND TRUTH as of the generation timestamp.**
**Do not make claims beyond what is proven by passing tests.**

REPORT_FOOTER

echo -e "${GREEN}✅ Report generated: $REPORT_FILE${NC}"
echo ""

# Display summary
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}📊 SUMMARY${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Working Validators: ${GREEN}$(jq -r '[.validators[] | select(.overall_status == "FULLY_WORKING")] | length' "$RESULTS_FILE")${NC}"
echo -e "Partial Validators: ${YELLOW}$(jq -r '[.validators[] | select(.overall_status == "PARTIALLY_WORKING")] | length' "$RESULTS_FILE")${NC}"
echo -e "Broken Validators:  ${RED}$(jq -r '[.validators[] | select(.overall_status == "BROKEN")] | length' "$RESULTS_FILE")${NC}"
echo ""
echo -e "Test Pass Rate: $(awk "BEGIN {printf \"%.1f%%\", ($PASSED/$TOTAL_TESTS)*100}")"
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"

exit 0
