#!/usr/bin/env tsx

/**
 * af apply-fixes
 * 
 * CLI command to apply code fix proposals generated by governance agent.
 * Supports filtering by risk level, dry-run mode, and pattern metrics logging.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as process from 'process';
import { loadAutoApplyPolicy, evaluateProposal, applyCodeFix, batchEvaluate, filterByDecision, logPolicyDecision } from '../tools/federation/auto_apply_policy.js';
import { CodeFixProposal } from '../tools/federation/code_fix_proposals.js';

// Parse command line arguments
interface Args {
  dryRun: boolean;
  riskLevel?: 'low' | 'medium' | 'high';
  pattern?: string;
  goalieDir: string;
  proposalsFile?: string;
  jsonOutput: boolean;
  autoApply: boolean;
  help: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    dryRun: false,
    goalieDir: path.resolve(process.cwd(), '.goalie'),
    jsonOutput: false,
    autoApply: false,
    help: false,
  };
  
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case '--dry-run':
        args.dryRun = true;
        break;
      case '--risk-level':
        args.riskLevel = argv[++i] as 'low' | 'medium' | 'high';
        break;
      case '--pattern':
        args.pattern = argv[++i];
        break;
      case '--goalie-dir':
        args.goalieDir = path.resolve(argv[++i]);
        break;
      case '--proposals-file':
        args.proposalsFile = argv[++i];
        break;
      case '--json':
        args.jsonOutput = true;
        break;
      case '--auto-apply':
        args.autoApply = true;
        break;
      case '--help':
      case '-h':
        args.help = true;
        break;
    }
  }
  
  return args;
}

function printHelp(): void {
  console.log(`
Usage: af apply-fixes [options]

Apply code fix proposals generated by governance agent.

Options:
  --dry-run              Preview fixes without applying them
  --risk-level LEVEL     Filter by risk level: low, medium, high
  --pattern PATTERN      Filter by pattern name (supports substring match)
  --goalie-dir DIR       Path to .goalie directory (default: ./.goalie)
  --proposals-file FILE  Load proposals from JSON file (default: latest governance output)
  --json                 Output results as JSON
  --auto-apply           Automatically apply approved fixes without confirmation
  --help, -h             Show this help message

Examples:
  # Preview all proposals
  af apply-fixes --dry-run

  # Apply only low-risk fixes automatically
  af apply-fixes --risk-level low --auto-apply

  # Preview fixes for specific pattern
  af apply-fixes --pattern observability --dry-run

  # Apply fixes with JSON output
  af apply-fixes --auto-apply --json

Environment Variables:
  AF_RUN_ID              Run identifier for pattern metrics
  AF_RUN_ITERATION       Current iteration number
  AF_CIRCLE              Circle context (default: governance)
`);
}

async function loadProposals(args: Args): Promise<CodeFixProposal[]> {
  let proposalsSource: string;
  
  if (args.proposalsFile) {
    proposalsSource = args.proposalsFile;
  } else {
    // Load from latest governance output
    const files = fs.readdirSync(args.goalieDir)
      .filter(f => f.startsWith('governance_output_') && f.endsWith('.json'))
      .sort()
      .reverse();
    
    if (files.length === 0) {
      throw new Error('No governance output files found. Run governance agent first.');
    }
    
    proposalsSource = path.join(args.goalieDir, files[0]);
  }
  
  console.log(`[apply-fixes] Loading proposals from: ${proposalsSource}`);
  
  const data = JSON.parse(fs.readFileSync(proposalsSource, 'utf8'));
  const proposals: CodeFixProposal[] = data.codeFixProposals || [];
  
  return proposals;
}

function filterProposals(proposals: CodeFixProposal[], args: Args): CodeFixProposal[] {
  let filtered = proposals;
  
  if (args.riskLevel) {
    filtered = filtered.filter(p => p.riskLevel === args.riskLevel);
    console.log(`[apply-fixes] Filtered to ${filtered.length} ${args.riskLevel}-risk proposals`);
  }
  
  if (args.pattern) {
    filtered = filtered.filter(p => p.pattern.includes(args.pattern!));
    console.log(`[apply-fixes] Filtered to ${filtered.length} proposals matching pattern '${args.pattern}'`);
  }
  
  return filtered;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  
  if (args.help) {
    printHelp();
    process.exit(0);
  }
  
  try {
    // Load policy
    const policy = loadAutoApplyPolicy(args.goalieDir);
    console.log(`[apply-fixes] Policy loaded - auto-apply ${policy.enabled ? 'enabled' : 'disabled'}`);
    
    // Override policy if dry-run
    if (args.dryRun) {
      console.log('[apply-fixes] Dry-run mode enabled - no files will be modified');
    }
    
    // Load proposals
    const proposals = await loadProposals(args);
    console.log(`[apply-fixes] Loaded ${proposals.length} total proposals`);
    
    if (proposals.length === 0) {
      console.log('[apply-fixes] No proposals to process');
      process.exit(0);
    }
    
    // Filter proposals
    const filtered = filterProposals(proposals, args);
    
    if (filtered.length === 0) {
      console.log('[apply-fixes] No proposals match the specified filters');
      process.exit(0);
    }
    
    // Evaluate proposals against policy
    const decisions = batchEvaluate(filtered, policy);
    
    // Categorize by decision
    const toApply = filterByDecision(decisions, 'apply');
    const dryRunDecisions = filterByDecision(decisions, 'dry-run');
    const manualDecisions = filterByDecision(decisions, 'manual');
    
    // Log decisions to pattern metrics
    for (const decision of decisions) {
      logPolicyDecision(decision, args.goalieDir);
    }
    
    // Emit pattern event for code-fix-proposal-batch
    emitBatchPatternEvent(args.goalieDir, decisions.length, toApply.length, dryRunDecisions.length, manualDecisions.length);
    
    // Print summary
    console.log('\\n=== Code Fix Proposals Summary ===');
    console.log(`Total evaluated: ${decisions.length}`);
    console.log(`Auto-apply approved: ${toApply.length}`);
    console.log(`Dry-run recommended: ${dryRunDecisions.length}`);
    console.log(`Manual approval required: ${manualDecisions.length}`);
    
    // Show proposals
    if (!args.jsonOutput) {
      console.log('\\n=== Proposals to Auto-Apply ===');
      for (const decision of toApply) {
        console.log(`  [${decision.proposal.riskLevel.toUpperCase()}] ${decision.proposal.pattern}`);
        console.log(`    ${decision.proposal.description}`);
        console.log(`    File: ${decision.proposal.filePath || 'N/A'}`);
        console.log(`    Reason: ${decision.reason}`);
      }
      
      if (manualDecisions.length > 0) {
        console.log('\\n=== Proposals Requiring Manual Approval ===');
        for (const decision of manualDecisions) {
          console.log(`  [${decision.proposal.riskLevel.toUpperCase()}] ${decision.proposal.pattern}`);
          console.log(`    ${decision.proposal.description}`);
          console.log(`    Reason: ${decision.reason}`);
        }
      }
    }
    
    // Apply fixes if not dry-run and auto-apply enabled
    if (!args.dryRun && (args.autoApply || policy.enabled) && toApply.length > 0) {
      console.log(`\\n=== Applying ${toApply.length} fixes ===`);
      
      const results = [];
      for (const decision of toApply) {
        const result = await applyCodeFix(decision.proposal, policy, args.goalieDir);
        results.push(result);
        
        // Emit pattern event for each applied fix
        emitCodeFixAppliedEvent(args.goalieDir, decision.proposal, result);
        
        if (result.success) {
          console.log(`  ✓ Applied: ${decision.proposal.pattern}`);
        } else {
          console.log(`  ✗ Failed: ${decision.proposal.pattern} - ${result.error}`);
        }
      }
      
      // Summary
      const successCount = results.filter(r => r.success).length;
      const failureCount = results.filter(r => !r.success).length;
      
      console.log(`\\n=== Application Results ===`);
      console.log(`Successful: ${successCount}`);
      console.log(`Failed: ${failureCount}`);
      
      if (args.jsonOutput) {
        console.log(JSON.stringify({ results }, null, 2));
      }
    } else if (args.jsonOutput) {
      console.log(JSON.stringify({
        summary: {
          total: decisions.length,
          autoApply: toApply.length,
          dryRun: dryRunDecisions.length,
          manual: manualDecisions.length,
        },
        decisions: decisions.map(d => ({
          proposalId: d.proposal.proposalId,
          pattern: d.proposal.pattern,
          riskLevel: d.proposal.riskLevel,
          decision: d.decision,
          reason: d.reason,
        })),
      }, null, 2));
    }
    
  } catch (error) {
    console.error(`[apply-fixes] Error: ${(error as Error).message}`);
    if (!args.jsonOutput) {
      console.error((error as Error).stack);
    }
    process.exit(1);
  }
}

function emitBatchPatternEvent(
  goalieDir: string,
  totalProposals: number,
  autoApplyCount: number,
  dryRunCount: number,
  manualCount: number
): void {
  const event = {
    ts: new Date().toISOString(),
    run: 'apply-fixes',
    run_id: process.env.AF_RUN_ID || `apply-${Date.now()}`,
    iteration: parseInt(process.env.AF_RUN_ITERATION || '0', 10),
    circle: process.env.AF_CIRCLE || 'governance',
    depth: 0,
    pattern: 'code-fix-batch',
    mode: autoApplyCount > 0 ? 'enforcement' : 'advisory',
    mutation: autoApplyCount > 0,
    gate: 'code-fix-application',
    framework: '',
    scheduler: '',
    tags: ['Federation', 'CodeFix'],
    economic: {
      cod: 0,
      wsjf_score: 0,
    },
    total_proposals: totalProposals,
    auto_apply_count: autoApplyCount,
    dry_run_count: dryRunCount,
    manual_count: manualCount,
  };
  
  const metricsPath = path.join(goalieDir, 'pattern_metrics.jsonl');
  try {
    fs.appendFileSync(metricsPath, JSON.stringify(event) + '\\n');
  } catch (err) {
    console.warn('[apply-fixes] Failed to emit batch pattern event:', err);
  }
}

function emitCodeFixAppliedEvent(
  goalieDir: string,
  proposal: CodeFixProposal,
  result: { success: boolean; error?: string; durationMs?: number }
): void {
  const event = {
    ts: new Date().toISOString(),
    run: 'apply-fixes',
    run_id: process.env.AF_RUN_ID || `apply-${Date.now()}`,
    iteration: parseInt(process.env.AF_RUN_ITERATION || '0', 10),
    circle: process.env.AF_CIRCLE || 'governance',
    depth: 0,
    pattern: 'code-fix-applied',
    mode: 'enforcement',
    mutation: true,
    gate: 'code-fix-execution',
    framework: '',
    scheduler: '',
    tags: ['Federation', 'CodeFix', proposal.pattern],
    economic: {
      cod: proposal.economic?.cod || 0,
      wsjf_score: proposal.economic?.wsjfScore || 0,
    },
    proposal_id: proposal.proposalId,
    proposal_pattern: proposal.pattern,
    risk_level: proposal.riskLevel,
    success: result.success,
    duration_ms: result.durationMs,
    error: result.error,
  };
  
  const metricsPath = path.join(goalieDir, 'pattern_metrics.jsonl');
  try {
    fs.appendFileSync(metricsPath, JSON.stringify(event) + '\\n');
  } catch (err) {
    console.warn('[apply-fixes] Failed to emit code-fix-applied event:', err);
  }
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
