#!/bin/bash
# =============================================================================
# Generate Internal Certificate Authority
# =============================================================================
# Purpose: Create a self-signed CA for off-host syslog mutual TLS authentication
# Validity: 10 years (3650 days)
# Key Size: 4096-bit RSA
# =============================================================================

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/generated"

# CA Configuration (can be overridden by environment variables)
CA_DAYS="${CA_DAYS:-3650}"
CA_KEY_SIZE="${CA_KEY_SIZE:-4096}"
CA_ORG="${CA_ORG:-Infrastructure}"
CA_UNIT="${CA_UNIT:-Observability}"
CA_CN="${CA_CN:-Off-Host Syslog Internal CA}"
CA_COUNTRY="${CA_COUNTRY:-US}"
CA_STATE="${CA_STATE:-California}"
CA_LOCALITY="${CA_LOCALITY:-San Francisco}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# =============================================================================
# Prerequisite Checks
# =============================================================================

check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v openssl &>/dev/null; then
        log_error "OpenSSL is required but not installed"
        exit 1
    fi
    
    # Verify we're running as root (for proper permissions)
    if [[ $EUID -ne 0 ]]; then
        log_warn "Not running as root - keys will be owned by current user"
        log_warn "For production, run: sudo $0"
    fi
    
    log_info "Prerequisites check passed"
}

# =============================================================================
# Create Output Directory
# =============================================================================

create_output_dir() {
    log_info "Creating output directory: ${OUTPUT_DIR}"
    
    mkdir -p "${OUTPUT_DIR}"
    chmod 700 "${OUTPUT_DIR}"
    
    # Create index and serial files for CA database
    touch "${OUTPUT_DIR}/index.txt"
    echo "1000" > "${OUTPUT_DIR}/serial"
}

# =============================================================================
# Generate OpenSSL Configuration
# =============================================================================

generate_openssl_config() {
    log_info "Generating OpenSSL configuration..."
    
    cat > "${OUTPUT_DIR}/ca.cnf" << EOF
# OpenSSL CA Configuration
# Generated by generate-ca.sh

[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = ${OUTPUT_DIR}
certs             = \$dir
crl_dir           = \$dir
new_certs_dir     = \$dir
database          = \$dir/index.txt
serial            = \$dir/serial
RANDFILE          = \$dir/.rand

private_key       = \$dir/ca.key
certificate       = \$dir/ca.crt

default_days      = 365
default_crl_days  = 30
default_md        = sha256
preserve          = no
policy            = policy_match

[ policy_match ]
countryName             = optional
stateOrProvinceName     = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ req ]
default_bits        = ${CA_KEY_SIZE}
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
string_mask         = utf8only
prompt              = no

[ req_distinguished_name ]
countryName                     = ${CA_COUNTRY}
stateOrProvinceName             = ${CA_STATE}
localityName                    = ${CA_LOCALITY}
0.organizationName              = ${CA_ORG}
organizationalUnitName          = ${CA_UNIT}
commonName                      = ${CA_CN}

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:1
keyUsage = critical, digitalSignature, cRLSign, keyCertSign

[ server_cert ]
basicConstraints = CA:FALSE
nsCertType = server
nsComment = "Off-Host Syslog Server Certificate"
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

[ client_cert ]
basicConstraints = CA:FALSE
nsCertType = client
nsComment = "Off-Host Syslog Client Certificate"
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
EOF
}

# =============================================================================
# Generate CA Key and Certificate
# =============================================================================

generate_ca() {
    log_info "Generating CA private key (${CA_KEY_SIZE}-bit RSA)..."
    
    # Check if CA already exists
    if [[ -f "${OUTPUT_DIR}/ca.key" ]]; then
        log_warn "CA key already exists at ${OUTPUT_DIR}/ca.key"
        read -p "Overwrite existing CA? [y/N]: " -r confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            log_info "Keeping existing CA"
            return 0
        fi
    fi
    
    # Generate CA private key
    openssl genrsa -out "${OUTPUT_DIR}/ca.key" ${CA_KEY_SIZE}
    
    # Set strict permissions on private key
    chmod 600 "${OUTPUT_DIR}/ca.key"
    if [[ $EUID -eq 0 ]]; then
        chown root:root "${OUTPUT_DIR}/ca.key"
    fi
    
    log_info "Generating CA certificate (valid for ${CA_DAYS} days)..."
    
    # Generate self-signed CA certificate
    openssl req -new -x509 \
        -days ${CA_DAYS} \
        -key "${OUTPUT_DIR}/ca.key" \
        -out "${OUTPUT_DIR}/ca.crt" \
        -config "${OUTPUT_DIR}/ca.cnf" \
        -extensions v3_ca
    
    # Set certificate permissions
    chmod 644 "${OUTPUT_DIR}/ca.crt"
    
    log_info "CA certificate generated successfully"
}

# =============================================================================
# Verify CA
# =============================================================================

verify_ca() {
    log_info "Verifying CA certificate..."
    
    # Display certificate information
    echo ""
    echo "=============================================="
    echo "CA Certificate Information"
    echo "=============================================="
    openssl x509 -in "${OUTPUT_DIR}/ca.crt" -noout -subject -issuer -dates
    echo ""
    
    # Verify self-signature
    if openssl verify -CAfile "${OUTPUT_DIR}/ca.crt" "${OUTPUT_DIR}/ca.crt" 2>&1 | grep -q "OK"; then
        log_info "CA certificate self-verification: PASSED"
    else
        log_error "CA certificate self-verification: FAILED"
        exit 1
    fi
}

# =============================================================================
# Output Summary
# =============================================================================

print_summary() {
    echo ""
    echo "=============================================="
    echo "CA Generation Complete"
    echo "=============================================="
    echo ""
    echo "Files created:"
    echo "  - ${OUTPUT_DIR}/ca.key (private key, 0600 permissions)"
    echo "  - ${OUTPUT_DIR}/ca.crt (certificate, 0644 permissions)"
    echo "  - ${OUTPUT_DIR}/ca.cnf (OpenSSL configuration)"
    echo ""
    echo "Next steps:"
    echo "  1. Run ./generate-server-cert.sh to create VPS server certificate"
    echo "  2. Run ./generate-client-cert.sh to create stx-aio-0 client certificate"
    echo ""
    echo "Security reminder:"
    echo "  - Keep ca.key in a secure location"
    echo "  - Do NOT commit ca.key to version control"
    echo "  - Backup ca.key securely for certificate renewal"
    echo ""
}

# =============================================================================
# Main
# =============================================================================

main() {
    echo "=============================================="
    echo "Off-Host Syslog - Internal CA Generator"
    echo "=============================================="
    echo ""
    
    check_prerequisites
    create_output_dir
    generate_openssl_config
    generate_ca
    verify_ca
    print_summary
}

main "$@"
