/**
 * test-plugin
 * Model-free value-based learning
 *
 * Generated by SQLite Vector Learning Plugin CLI
 */

import type { LearningPlugin, PluginConfig, Experience, Vector, Action } from 'agentdb/plugins';
import { TestPluginAgent } from './agent.mjs';

export class TestPluginPlugin implements LearningPlugin {
  name = 'test-plugin';
  version = '1.0.0';
  config: PluginConfig;

  private agent: TestPluginAgent;

  async initialize(config: PluginConfig): Promise<void> {
    this.config = config;
    this.agent = new TestPluginAgent(config);
    await this.agent.initialize();
  }

  async destroy(): Promise<void> {
    await this.agent.destroy();
  }

  async storeExperience(experience: Experience): Promise<void> {
    await this.agent.storeExperience(experience);
  }

  async storeBatch(experiences: Experience[]): Promise<void> {
    await this.agent.storeBatch(experiences);
  }

  async retrieveSimilar(state: Vector, k: number): Promise<Experience[]> {
    return await this.agent.retrieveSimilar(state, k);
  }

  async selectAction(state: Vector, context?: any): Promise<Action> {
    return await this.agent.selectAction(state, context);
  }

  async train(options?: any): Promise<any> {
    return await this.agent.train(options);
  }

  async getMetrics(): Promise<any> {
    return await this.agent.getMetrics();
  }

  getConfig(): PluginConfig {
    return this.config;
  }

  async save(path: string): Promise<void> {
    await this.agent.save(path);
  }

  async load(path: string): Promise<void> {
    await this.agent.load(path);
  }
}

// Export plugin factory
export default function createPlugin(config: PluginConfig): LearningPlugin {
  return new TestPluginPlugin();
}
