# Ansible Inventory for Off-Host Syslog Black Box Recorder

[syslog_sink]
 ansible_user=root ansible_port=22

[syslog_client]
stx-aio-0.corp.interface.tag.ooo ansible_user=ubuntu ansible_port=22

[all:vars]
ansible_python_interpreter=/usr/bin/python3
admin_ip=173.94.53.113
syslog_port=6514
