#!/bin/bash
# Phase 1.1: Multi-Tenant Domain Routing Infrastructure Setup
# Target: stx-aio-0.corp.interface.tag.ooo
# WSJF: 15.0 (Highest Priority)
# Pattern: strangler-fig (gradually replace IP routing)

set -e

echo "🚀 Phase 1.1: Multi-Tenant Domain Routing Setup"
echo "Target Server: stx-aio-0.corp.interface.tag.ooo"
echo "Pattern: strangler-fig | WSJF: 15.0"
echo ""

# Configuration
STX_HOST="stx-aio-0.corp.interface.tag.ooo"
DOMAINS=(
    "DecisionCall.com"
    "analytics.interface.tag.ooo"
    "half.masslessmassive.com"
    "multi.masslessmassive.com"
)

# Check if running locally or on stx-aio-0
if [[ "$(hostname)" == "stx-aio-0"* ]]; then
    LOCAL=true
    echo "✅ Running on stx-aio-0 directly"
else
    LOCAL=false
    echo "⚠️  Running remotely - will use SSH"
    read -p "Enter SSH key path for stx-aio-0 [~/pem/stx-aio-0.pem]: " SSH_KEY
    SSH_KEY=${SSH_KEY:-~/pem/stx-aio-0.pem}
    
    if [ ! -f "$SSH_KEY" ]; then
        echo "❌ SSH key not found: $SSH_KEY"
        exit 1
    fi
fi

# Function to execute commands (local or remote)
exec_cmd() {
    if [ "$LOCAL" = true ]; then
        eval "$1"
    else
        ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no root@"$STX_HOST" "$1"
    fi
}

echo ""
echo "📋 Step 1: Check existing web server configuration"
echo "================================================================"

# Detect if nginx or apache is running
WEB_SERVER=$(exec_cmd "systemctl is-active nginx 2>/dev/null && echo 'nginx' || (systemctl is-active httpd 2>/dev/null && echo 'apache' || echo 'none')")

echo "Detected web server: $WEB_SERVER"

if [ "$WEB_SERVER" = "none" ]; then
    echo "⚙️  No web server detected. Installing nginx..."
    exec_cmd "yum install -y nginx || apt-get install -y nginx"
    exec_cmd "systemctl enable nginx"
    exec_cmd "systemctl start nginx"
    WEB_SERVER="nginx"
fi

echo ""
echo "📋 Step 2: Install Certbot for Let's Encrypt SSL"
echo "================================================================"

exec_cmd "yum install -y certbot python3-certbot-nginx || apt-get install -y certbot python3-certbot-nginx"

echo ""
echo "📋 Step 3: Create nginx configuration for multi-tenant domains"
echo "================================================================"

# Create nginx config template
cat > /tmp/nginx_multitenant.conf << 'EOF'
# Multi-Tenant Domain Routing Configuration
# Generated by phase1_domain_routing.sh

# Upstream backend pools
upstream decisioncall_backend {
    server 127.0.0.1:8001;
    keepalive 32;
}

upstream analytics_backend {
    server 127.0.0.1:8002;
    keepalive 32;
}

upstream half_backend {
    server 127.0.0.1:8003;
    keepalive 32;
}

upstream multi_backend {
    server 127.0.0.1:8004;
    keepalive 32;
}

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name DecisionCall.com www.DecisionCall.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 80;
    server_name analytics.interface.tag.ooo;
    return 301 https://$server_name$request_uri;
}

server {
    listen 80;
    server_name half.masslessmassive.com *.half.masslessmassive.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 80;
    server_name multi.masslessmassive.com *.multi.masslessmassive.com;
    return 301 https://$server_name$request_uri;
}

# HTTPS configurations (SSL certs will be added by Certbot)
server {
    listen 443 ssl http2;
    server_name DecisionCall.com www.DecisionCall.com;
    
    # SSL certificates (will be managed by Certbot)
    # ssl_certificate /etc/letsencrypt/live/DecisionCall.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/DecisionCall.com/privkey.pem;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    location / {
        proxy_pass http://decisioncall_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    
    access_log /var/log/nginx/decisioncall_access.log;
    error_log /var/log/nginx/decisioncall_error.log;
}

server {
    listen 443 ssl http2;
    server_name analytics.interface.tag.ooo;
    
    location / {
        proxy_pass http://analytics_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    
    access_log /var/log/nginx/analytics_access.log;
    error_log /var/log/nginx/analytics_error.log;
}

server {
    listen 443 ssl http2;
    server_name half.masslessmassive.com *.half.masslessmassive.com;
    
    location / {
        proxy_pass http://half_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    
    access_log /var/log/nginx/half_access.log;
    error_log /var/log/nginx/half_error.log;
}

server {
    listen 443 ssl http2;
    server_name multi.masslessmassive.com *.multi.masslessmassive.com;
    
    location / {
        proxy_pass http://multi_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    
    access_log /var/log/nginx/multi_access.log;
    error_log /var/log/nginx/multi_error.log;
}

# Tenant isolation - subdomain routing
# Pattern: <tenant>.half.masslessmassive.com -> half_backend with tenant header
# Pattern: <tenant>.multi.masslessmassive.com -> multi_backend with tenant header
EOF

# Copy config to server
if [ "$LOCAL" = true ]; then
    cp /tmp/nginx_multitenant.conf /etc/nginx/conf.d/multitenant.conf
else
    scp -i "$SSH_KEY" /tmp/nginx_multitenant.conf root@"$STX_HOST":/etc/nginx/conf.d/multitenant.conf
fi

echo "✅ Nginx configuration deployed"

echo ""
echo "📋 Step 4: Test nginx configuration"
echo "================================================================"

if ! exec_cmd "nginx -t"; then
    echo "❌ Nginx configuration test failed"
    exit 1
fi

echo "✅ Nginx configuration valid"

echo ""
echo "📋 Step 5: Request SSL certificates from Let's Encrypt"
echo "================================================================"

echo "⚠️  DNS records must be configured before requesting certificates:"
for domain in "${DOMAINS[@]}"; do
    echo "  • $domain -> $(exec_cmd 'curl -s ifconfig.me')"
done

read -p "Are DNS records configured? (yes/no): " DNS_READY

if [ "$DNS_READY" != "yes" ]; then
    echo "⚠️  Skipping SSL certificate generation"
    echo "Run this script again after DNS is configured"
else
    for domain in "${DOMAINS[@]}"; do
        echo "Requesting certificate for $domain..."
        exec_cmd "certbot --nginx -d $domain -d www.$domain --non-interactive --agree-tos --email admin@$domain || true"
    done
fi

echo ""
echo "📋 Step 6: Reload nginx"
echo "================================================================"

exec_cmd "systemctl reload nginx"

echo ""
echo "📋 Step 7: Set up certificate auto-renewal"
echo "================================================================"

exec_cmd "systemctl enable certbot-renew.timer || (echo '0 0,12 * * * root certbot renew --quiet' | tee -a /etc/crontab)"

echo ""
echo "✅ Phase 1.1 Domain Routing Setup Complete!"
echo ""
echo "📊 Summary:"
echo "  Web Server: $WEB_SERVER"
echo "  Configured Domains:"
for domain in "${DOMAINS[@]}"; do
    echo "    • https://$domain -> Backend port mapping"
done
echo ""
echo "🔧 Next Steps:"
echo "  1. Deploy backend services on ports 8001-8004"
echo "  2. Configure HostBill tenant provisioning API"
echo "  3. Test multi-tenant routing with curl/browser"
echo "  4. Run observability checks: ./scripts/af detect-observability-gaps"
echo ""
echo "📝 Backend Port Mapping:"
echo "  8001 -> DecisionCall.com"
echo "  8002 -> analytics.interface.tag.ooo"
echo "  8003 -> half.masslessmassive.com"
echo "  8004 -> multi.masslessmassive.com"
